# Character Encoding

## Content characters

The content of a Stan program must be coded in ASCII.  All identifiers
must consist of only ASCII alpha-numeric characters and the underscore
character.  All arithmetic operators and punctuation must be coded in
ASCII.

### Compatibility with Latin-1 and UTF-8 {-}

The UTF-8 encoding of Unicode and the Latin-1 (ISO-8859-1) encoding
share the first 128 code points with ASCII and thus cannot be
distinguished from ASCII.  That means you can set editors, etc., to
use UTF-8 or Latin-1 (or the other Latin-n variants) without worrying
that the content of a Stan program will be destroyed.

## Comment characters

Any bytes on a line after a line-comment sequence (`//` or
`#`) are ignored up until the ASCII newline character
(`\n`).  They may thus be written in any character encoding which
is convenient.

Any content after a block comment open sequence in ASCII (`/*`)
up to the closing block comment (`*/`) is ignored, and thus may
also be written in whatever character set is convenient.

## String literals

String literals are escaped according to the C++ standard.
In particular, this means that bytes outside of the ASCII character
range in a `print` or `reject` statement should properly be displayed
if your terminal supports the encoding used in the input. In other
words, Stan simply preserves any string of bytes between two double
quotes (`"`) when passing to C++. On compliant terminals, this allows
the use of glyphs and other characters from encodings such as UTF-8 that
fall outside the ASCII-compatible range.

The recommended character encoding for portable code that should
display properly on all systems is still ASCII.