---
pagetitle: Glossary
---

This glossary offers simplified explanations of common technical terms found
in Stan's documentation and interfaces. The glossary will aid users that are
familiar with basic concepts in Bayesian inference and computation, but
unfamiliar with Stan's vocabulary.

The explanations included here are not intended to be exhaustive or detailed.
For more information, consult our chapter [*How to Diagnose and Resolve
Convergence
Problems*](https://mc-stan.org/learn-stan/diagnostics-warnings.html) or our
section [*Algorithms*](https://mc-stan.org/docs/reference-manual/mcmc.html)
in the Reference Manual.

**Bulk ESS** A version of the effective sample size that measures the
reliability of the center, or "bulk", of the posterior distribution, i.e., the
region summarized by a mean or a median. A high bulk ESS indicates that
estimates of the distribution's central tendency are reliable. See also:
*Effective sample size*, *Tail ESS*.

**Chain** An ordered sequence of random draws produced by a sampler to
describe a posterior distribution (see a formal definition
[here](https://mc-stan.org/docs/reference-manual/analysis.html#markov-chains)).
Fitting a model typically involves several chains running in parallel, which
lets us check that they agree with one another. See also: *Iteration*, *Monte
Carlo standard error (MCSE)*, *R-hat*.

**Divergence** A warning that the sampler ran into trouble and may have
skipped part of the posterior distribution. Skipping this region biases the
posterior sample and hinders inferences. So, divergences signal that the draws
may be unreliable---even if the R-hat and effective sample size look fine. The
Reference Manual offers a more formal explanation
[here](https://mc-stan.org/docs/reference-manual/mcmc.html#divergent-transitions).
And Stan's [*Learning Resources on Diagnostics and
warnings*](https://mc-stan.org/learn-stan/diagnostics-warnings.html#divergent-transitions-after-warmup)
explicate some causes and solutions. See also: *Maximum tree depth*,
*Reparametrize*.

**Effective sample size (ESS)** A measure of how much information a set of
draws actually provides. Draws within a chain tend to be related to one
another, making them less informative than the same number of independent
draws would be. For a given number of draws in a model, the ESS reports the
equivalent number of independent draws. The [chapter on Posterior
Analysis](https://mc-stan.org/docs/reference-manual/analysis.html#effective-sample-size.section)
of the Reference Manual offers a formal definition. And our chapter on
*How to Diagnose and Resolve Convergence Problems*
[suggests](https://mc-stan.org/learn-stan/diagnostics-warnings.html#bulk-and-tail-ess)
some useful thresholds. See also: *Bulk ESS*, *Tail ESS*.

**Iteration** A single step in a sampler's computational process. Each step
produces one draw in a chain. The total number of iterations includes warmup
iterations, which are discarded; and post-warmup iterations, which are kept
for analysis. See also: *Chain*, *Warmup*.

**Maximum treedepth** A limit on how long Stan’s NUTS sampler may search for a
new draw during each iteration. If the sampler repeatedly reaches this limit,
it may be stopping its search too early and exploring the posterior
inefficiently. See more details
[here](https://mc-stan.org/learn-stan/diagnostics-warnings.html#maximum-treedepth)
and suggestions for dealing with this problem in point 7
[here](https://mc-stan.org/learn-stan/diagnostics-warnings.html#diagnosing-and-resolving-problems).
See also: *Divergence*, *Reparametrize*.

**Monte Carlo standard error (MCSE)** A measure of the uncertainty of the
Monte Carlo samples used to get the posterior mean of a parameter. Stan relies
on Monte Carlo random sampling, so different runs of the same simulation can
yield different results. The MCSE quantifies how much an estimate (such as a
posterior mean) is expected to fluctuate due to this randomness. See a formal
definition
[here](https://mc-stan.org/docs/reference-manual/analysis.html#estimation-of-mcmc-standard-error).
For final results, the MCSE should be small enough not to affect the digits
intended for reporting. So, if we plan to report two decimal places, the MCSE
should be below $0.01$. See also: *Effective sample size*, *Iteration*.

**R-hat** A diagnostic that evaluates whether multiple chains have converged
to the same posterior distribution. R-hat compares the variation of draws
within each chain to the variation across different chains. When chains
converge, these two types of variation become roughly equal, so R-hat gets
close to 1. When chains diverge, the variation across different chains is
larger than the variation within chains, so R-hat is above 1. See a formal
definition in [this paper](https://arxiv.org/abs/1903.08008) and some useful
thresholds [here](https://mc-stan.org/learn-stan/diagnostics-warnings.html#r-hat).
See also: *Chain*.

**Reparametrize** To rewrite a model in a different but mathematically
equivalent form. Stan can often represent a given model in multiple ways, some
of which are easier to sample than others. For example, centering a continuous
predictor by subtracting its mean leaves the fitted model unchanged but
reduces the posterior dependency between the intercept and the slope.
Reparametrizing a model can help avoid divergences and increase effective
sample sizes. See
[here](https://mc-stan.org/docs/stan-users-guide/reparameterization.html)
for examples in Stan, and see point 15
[here](https://mc-stan.org/learn-stan/diagnostics-warnings.html#diagnosing-and-resolving-problems)
for more resources. See also: *Divergence*, *Effective sample size*,
*Maximum tree depth*.

**Tail ESS** A version of the effective sample size that measures the
reliability of the tails of the posterior distribution, i.e., the regions
summarized by the 5% or 95% posterior quantiles. A high tail ESS indicates
that these quantiles are reliable. See also: *Bulk ESS*,
*Effective sample size*.

**Warmup** An initial set of iterations that are discarded rather than used
for analysis. Early draws in a chain are usually too inaccurate to describe
the posterior distribution reliably, so the sampler uses this warmup period to
settle into the region of plausible parameter values before collecting the
draws that are kept. See also: *Iteration*.