---
pagetitle: The Stan Ecosystem
---

# The Stan Ecosystem {#ecosystem.chapter}

Stan is a domain-specific tool for specifying probability models,
performing statistical inference and analyzing model fits.  Stan is
largely used for Bayesian models with Monte Carlo-based inference, but
it may also be used to fit penalized maximum likelihood estimates and
estimate confidence intervals with the bootstrap with optimization.


## Stan community

Stan has an active community of users and developers.

* [Stan forums](https://discourse.mc-stan.org), where users and
  developers discuss issues with Stan and its applications.  

* [Stan GitHub](https://github.com/stan-dev), which tracks issues and
  contains the complete source code for Stan (under the BSD-3
  license).

* [StanCon](https://mc-stan.org/learn-stan/stancon-talks.html), for
  which talks and executable notebooks are available.


## Stan documentation

Stan's documentation is organized through a top-level web page:

* [Stan documentation](https://mc-stan.org/docs/)

This is the *User's Guide*, which is complemented by the *Reference
Manual* and *Functions Reference*.  These are all interface-agnostic
guides to the Stan language and its execution.  They are available at

* [*Stan Users' Guide*](https://mc-stan.org/docs/stan-users-guide/)
documentation.

* [*Stan Reference
  Manual*](https://mc-stan.org/docs/reference-manual/)

* [*Stan Functions Reference*](https://mc-stan.org/docs/functions-reference/)

Documentation for the specific Stan interfaces are here

* [*CmdStan User's Guide*](https://mc-stan.org/docs/cmdstan-guide/)

* [*CmdstanPy Users's Guide*](https://mc-stan.org/cmdstanpy/)

* [*CmdStanR Users' Guide*](https://mc-stan.org/cmdstanr/)

* [*Stan.jl User's Guide*](

* [*PyStan User's Guide*](https://pystan.readthedocs.io/en/latest/)

* [*RStan User's Guide*](https://mc-stan.org/rstan/)

* [*Julia Interface User's Guide*](http://stanjulia.github.io/Stan.jl/stable/INTRO/)


## Stan programming language

Stan provides a domain-specific language for specifying smooth,
data-dependent probability functions on the logarithmic scale.  For
Bayesian models, this will be the posterior log density function (up
to an additive constant); in a frequentist setting, it will be a
penalized (marginal) likelihood function.

Stan is a differentiable programming language, meaning that Stan can
automatically take first, second, and even higher-order derivatives of
any log density it defines.  Stan is also a probabilistic programming
language in that its variables represent random variables and
constants.

## Stan inference

Stan supports inference for probability models through general,
model-agnostic sampling techniques including Markov chain Monte Carlo
(MCMC), variational inference (VI), and Laplace approximation.  Stan
can also be used to calculate a (penalized) maximum likelihood
estimate (MLE) using optimization and estimate confidence intervals
through the bootstrap.


## Stan math library

A program written in the Stan language is translated (aka transpiled)
to a C++ class defining a statistical model.  This C++ class depends
on the Stan Math Library, which implements differentiable arithmetic
operations, matrix and linear algebra operations, special mathematical
functions, and special statistical functions.  The Stan math library
itself has limited dependencies: Intel Thread Building Blocks for
synchronizing parallelism, Boost for general C++ tooling and special
functions, Eigen for matrix operations and linear algebra solvers, and
Sundials for differential equation solvers.


## Stan interfaces

### BridgeStan language interface

BridgeStan provides a complete interface to a Stan program through
Python, R, Julia, and Rust.  BridgeStan supports evaluation of the log
density and its first-order derivatives (gradients) and second-order
derivatives (Hessian).  It also provides I/O interface code for
constraining and unconstraining transforms and the simulation required
for posterior predictive inference.

BridgeStan is implemented through low-level foreign function
interfaces that link to the compiled C++ class for a Stan program.

### CmdStan reference interface

Several Stan interfaces provide posterior (predictive) inference
through Monte Carlo methods, variational methods, and Laplace
approximation. The reference implementation is CmdStan, which provides
a command-line interface (CLI) for Stan.

### CmdStan wrappers

Several of Stan's interfaces wrap CmdStan and call it as an external
process, including  CmdStanPy (Python), CmdStanR (R), Stan.jl (Julia),
and StataStan (Stata).  These interfaces are straightforward to update
with new versions of Stan as only CmdStan is required.

### In-memory interfaces

RStan (R) and PyStan (Python), were the first two interfaces developed
after CmdStan, and both provide in-memory and in-process calls to the
underlying C++.  Unlike BridgeStan, these in-memory interfaces are
coded using the language's high-level C++ interfaces (Rcpp and Cython,
respectively).  Like CmdStan and its wrappers, RStan and PyStan
require a C++ toolchain at runtime to compile models.

One advantage of RStan is that it encapsulates much of the
functionality of BridgeStan, allows the execution of Stan functions in
R through Rcpp, and supports the development of packages that can be
distributed with precomputed models and thus not depend on a C++
toolchain at runtime.

