project:
  title: "Stan Functions Reference"
  type: book

bibliography: [../bibtex/all.bib]
biblio-style: apalike
toc: true
toc-depth: 2

format:
  pdf:
    latex-tinytex: false
    block-headings: false
    pdf-engine: "pdflatex"
    latex-engine: "pdflatex"
    documentclass: book
    subtitle: "Version {{< env STAN_DOCS_VERSION >}}"
    include-in-header: "../header.tex"
    include-after-body: "../postamble.tex"
    toc-title: "Table of Contents"
    syntax-definitions:
      - ../theming/stan.xml
    keep-tex: false
    highlight-style: tango
    colorlinks: true
    linkcolor: darkblue
    urlcolor: darkblue
    citecolor: darkgreen

book:
  title: "Stan Functions Reference"
  author: "Stan Development Team"
  search: true

  chapters:
    - index.qmd
    - part: "Built-in Functions"
      chapters:
        - void_functions.qmd
        - integer-valued_basic_functions.qmd
        - real-valued_basic_functions.qmd
        - complex-valued_basic_functions.qmd
        - array_operations.qmd
        - matrix_operations.qmd
        - complex_matrix_operations.qmd
        - sparse_matrix_operations.qmd
        - mixed_operations.qmd
        - compound_arithmetic_and_assignment.qmd
        - higher-order_functions.qmd
        - deprecated_functions.qmd
        - removed_functions.qmd
        - conventions_for_probability_functions.qmd
    - part: "Discrete Distributions"
      chapters:
        - binary_distributions.qmd
        - bounded_discrete_distributions.qmd
        - unbounded_discrete_distributions.qmd
        - multivariate_discrete_distributions.qmd
    - part: "Continuous Distributions"
      chapters:
        - unbounded_continuous_distributions.qmd
        - positive_continuous_distributions.qmd
        - positive_lower-bounded_distributions.qmd
        - continuous_distributions_on_0_1.qmd
        - circular_distributions.qmd
        - bounded_continuous_distributions.qmd
        - distributions_over_unbounded_vectors.qmd
        - simplex_distributions.qmd
        - correlation_matrix_distributions.qmd
        - covariance_matrix_distributions.qmd
    - part: "Additional Distributions"
      chapters:
        - hidden_markov_models.qmd
    - part: "Appendix"
      chapters:
        - mathematical_functions.qmd
    - references.qmd
