# Mathematical Functions {#math-functions}

This appendix provides the definition of several mathematical
functions used throughout the manual.

```{r results='asis', echo=FALSE}
if (knitr::is_html_output()) {
cat(' * <a href="beta-appendix.html">Beta</a>\n')
cat(' * <a href="inc-beta-appendix.html">Incomplete Beta</a>\n')
cat(' * <a href="gamma-appendix.html">Gamma</a>\n')
cat(' * <a href="digamma-appendix.html">Digamma</a>\n')
}
```

## Beta {#beta-appendix}

The beta function, $\text{B}(a, b)$, computes the normalizing
constant for the beta distribution, and is defined for $a > 0$ and $b
> 0$ by \begin{equation*} \text{B}(a,b) \ = \ \int_0^1 u^{a - 1} (1 - u)^{b - 1} \,
du \ = \ \frac{\Gamma(a) \, \Gamma(b)}{\Gamma(a+b)} \, , \end{equation*}
where $\Gamma(x)$ is the [Gamma function](#gamma-appendix).

## Incomplete beta {#inc-beta-appendix}

The incomplete beta function, $\text{B}(x; a, b)$, is defined for $x
\in [0, 1]$ and $a, b \geq 0$ such that $a + b \neq 0$ by \begin{equation*}
\text{B}(x; \, a, b) \ = \ \int_0^x u^{a - 1} \, (1 - u)^{b - 1} \,
du, \end{equation*} where $\text{B}(a, b)$ is the beta function defined in
[appendix](#beta-appendix).  If $x = 1$, the incomplete beta function
reduces to the beta function, $\text{B}(1; a, b) = \text{B}(a, b)$.

The regularized incomplete beta function divides the incomplete beta
function by the beta function, \begin{equation*} I_x(a, b) \ = \ \frac{\text{B}(x; \,
a, b)}{B(a, b)} \, . \end{equation*}

## Gamma {#gamma-appendix}

The gamma function, $\Gamma(x)$, is the generalization of the
factorial function to continuous variables, defined so that for
positive integers $n$, \begin{equation*} \Gamma(n+1) = n! \end{equation*} Generalizing to all
positive numbers and non-integer negative numbers, \begin{equation*} \Gamma(x) =
\int_0^{\infty} u^{x - 1} \exp(-u) \, du. \end{equation*}

## Digamma {#digamma-appendix}

The digamma function $\Psi$ is the derivative of the $\log \Gamma$
function,
\begin{equation*}
\Psi(u) \ = \ \frac{d}{d u} \log \Gamma(u) \ = \ \frac{1}{\Gamma(u)} \ \frac{d}{d u} \Gamma(u).
\end{equation*}

