# Positive Lower-Bounded Distributions

The positive lower-bounded probabilities have support on real values
above some positive minimum value.

```{r results='asis', echo=FALSE}
if (knitr::is_html_output()) {
cat(' * <a href="pareto-distribution.html">Pareto Distribution</a>\n')
cat(' * <a href="pareto-type-2-distribution.html">Pareto Type 2 Distribution</a>\n')
cat(' * <a href="wiener-first-passage-time-distribution.html">Wiener First Passage Time Distribution</a>\n')
}
```

## Pareto distribution

### Probability density function

If $y_{\text{min}} \in \mathbb{R}^+$ and $\alpha \in \mathbb{R}^+$,
then for $y \in \mathbb{R}^+$ with $y \geq y_{\text{min}}$, \[
\text{Pareto}(y|y_{\text{min}},\alpha) = \frac{\displaystyle
\alpha\,y_{\text{min}}^\alpha}{\displaystyle y^{\alpha+1}}. \]

### Sampling statement

`y ~ ` **`pareto`**`(y_min, alpha)`

Increment target log probability density with `pareto_lupdf(y | y_min, alpha)`.
<!-- real; pareto ~; -->
\index{{\tt \bfseries pareto }!sampling statement|hyperpage}

### Stan functions

<!-- real; pareto_lpdf; (reals y | reals y_min, reals alpha); -->
\index{{\tt \bfseries pareto\_lpdf }!{\tt (reals y \textbar\ reals y\_min, reals alpha): real}|hyperpage}

`real` **`pareto_lpdf`**`(reals y | reals y_min, reals alpha)`<br>\newline
The log of the Pareto density of y given positive minimum value y_min
and shape alpha

<!-- real; pareto_lupdf; (reals y | reals y_min, reals alpha); -->
\index{{\tt \bfseries pareto\_lupdf }!{\tt (reals y \textbar\ reals y\_min, reals alpha): real}|hyperpage}

`real` **`pareto_lupdf`**`(reals y | reals y_min, reals alpha)`<br>\newline
The log of the Pareto density of y given positive minimum value y_min
and shape alpha dropping constant additive terms

<!-- real; pareto_cdf; (reals y, reals y_min, reals alpha); -->
\index{{\tt \bfseries pareto\_cdf }!{\tt (reals y, reals y\_min, reals alpha): real}|hyperpage}

`real` **`pareto_cdf`**`(reals y, reals y_min, reals alpha)`<br>\newline
The Pareto cumulative distribution function of y given positive
minimum value y_min and shape alpha

<!-- real; pareto_lcdf; (reals y | reals y_min, reals alpha); -->
\index{{\tt \bfseries pareto\_lcdf }!{\tt (reals y \textbar\ reals y\_min, reals alpha): real}|hyperpage}

`real` **`pareto_lcdf`**`(reals y | reals y_min, reals alpha)`<br>\newline
The log of the Pareto cumulative distribution function of y given
positive minimum value y_min and shape alpha

<!-- real; pareto_lccdf; (reals y | reals y_min, reals alpha); -->
\index{{\tt \bfseries pareto\_lccdf }!{\tt (reals y \textbar\ reals y\_min, reals alpha): real}|hyperpage}

`real` **`pareto_lccdf`**`(reals y | reals y_min, reals alpha)`<br>\newline
The log of the Pareto complementary cumulative distribution function
of y given positive minimum value y_min and shape alpha

<!-- R; pareto_rng; (reals y_min, reals alpha); -->
\index{{\tt \bfseries pareto\_rng }!{\tt (reals y\_min, reals alpha): R}|hyperpage}

`R` **`pareto_rng`**`(reals y_min, reals alpha)`<br>\newline
Generate a Pareto variate with positive minimum value y_min and shape
alpha; may only be used in transformed data and generated quantities blocks. For a
description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).

## Pareto type 2 distribution

### Probability density function

If $\mu \in \mathbb{R}$, $\lambda \in \mathbb{R}^+$, and $\alpha \in
\mathbb{R}^+$, then for $y \geq \mu$, \[
\mathrm{Pareto\_Type\_2}(y|\mu,\lambda,\alpha) = \
\frac{\alpha}{\lambda} \, \left( 1+\frac{y-\mu}{\lambda}
\right)^{-(\alpha+1)} \! . \]

Note that the Lomax distribution is a Pareto Type 2 distribution with
$\mu=0$.

### Sampling statement

`y ~ ` **`pareto_type_2`**`(mu, lambda, alpha)`

Increment target log probability density with `pareto_type_2_lupdf(y | mu, lambda, alpha)`.
<!-- real; pareto_type_2 ~; -->
\index{{\tt \bfseries pareto\_type\_2 }!sampling statement|hyperpage}

### Stan functions

<!-- real; pareto_type_2_lpdf; (reals y | reals mu, reals lambda, reals alpha); -->
\index{{\tt \bfseries pareto\_type\_2\_lpdf }!{\tt (reals y \textbar\ reals mu, reals lambda, reals alpha): real}|hyperpage}

`real` **`pareto_type_2_lpdf`**`(reals y | reals mu, reals lambda, reals alpha)`<br>\newline
The log of the Pareto Type 2 density of y given location mu, scale
lambda, and shape alpha

<!-- real; pareto_type_2_lupdf; (reals y | reals mu, reals lambda, reals alpha); -->
\index{{\tt \bfseries pareto\_type\_2\_lupdf }!{\tt (reals y \textbar\ reals mu, reals lambda, reals alpha): real}|hyperpage}

`real` **`pareto_type_2_lupdf`**`(reals y | reals mu, reals lambda, reals alpha)`<br>\newline
The log of the Pareto Type 2 density of y given location mu, scale
lambda, and shape alpha dropping constant additive terms

<!-- real; pareto_type_2_cdf; (reals y, reals mu, reals lambda, reals alpha); -->
\index{{\tt \bfseries pareto\_type\_2\_cdf }!{\tt (reals y, reals mu, reals lambda, reals alpha): real}|hyperpage}

`real` **`pareto_type_2_cdf`**`(reals y, reals mu, reals lambda, reals alpha)`<br>\newline
The Pareto Type 2 cumulative distribution function of y given location
mu, scale lambda, and shape alpha

<!-- real; pareto_type_2_lcdf; (reals y | reals mu, reals lambda, reals alpha); -->
\index{{\tt \bfseries pareto\_type\_2\_lcdf }!{\tt (reals y \textbar\ reals mu, reals lambda, reals alpha): real}|hyperpage}

`real` **`pareto_type_2_lcdf`**`(reals y | reals mu, reals lambda, reals alpha)`<br>\newline
The log of the Pareto Type 2 cumulative distribution function of y
given location mu, scale lambda, and shape alpha

<!-- real; pareto_type_2_lccdf; (reals y | reals mu, reals lambda, reals alpha); -->
\index{{\tt \bfseries pareto\_type\_2\_lccdf }!{\tt (reals y \textbar\ reals mu, reals lambda, reals alpha): real}|hyperpage}

`real` **`pareto_type_2_lccdf`**`(reals y | reals mu, reals lambda, reals alpha)`<br>\newline
The log of the Pareto Type 2 complementary cumulative distribution
function of y given location mu, scale lambda, and shape alpha

<!-- R; pareto_type_2_rng; (reals mu, reals lambda, reals alpha); -->
\index{{\tt \bfseries pareto\_type\_2\_rng }!{\tt (reals mu, reals lambda, reals alpha): R}|hyperpage}

`R` **`pareto_type_2_rng`**`(reals mu, reals lambda, reals alpha)`<br>\newline
Generate a Pareto Type 2 variate with location mu, scale lambda, and
shape alpha; may only be used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).

## Wiener First Passage Time Distribution

### Probability density function

If $\alpha \in \mathbb{R}^+$, $\tau \in \mathbb{R}^+$, $\beta \in [0,
1]$ and $\delta \in \mathbb{R}$, then for $y > \tau$, \[
\text{Wiener}(y|\alpha, \tau, \beta, \delta) =
\frac{\alpha^3}{(y-\tau)^{3/2}} \exp \! \left(- \delta \alpha \beta -
\frac{\delta^2(y-\tau)}{2}\right) \sum_{k = - \infty}^{\infty} (2k +
\beta) \phi \! \left(\frac{2k \alpha + \beta}{\sqrt{y - \tau}}\right)
\] where $\phi(x)$ denotes the standard normal density function;  see
[@Feller1968], [@NavarroFuss2009].

### Sampling statement

`y ~ ` **`wiener`**`(alpha, tau, beta, delta)`

Increment target log probability density with `wiener_lupdf(y | alpha, tau, beta, delta)`.
<!-- real; wiener ~; -->
\index{{\tt \bfseries wiener }!sampling statement|hyperpage}

### Stan functions

<!-- real; wiener_lpdf; (reals y | reals alpha, reals tau, reals beta, reals delta); -->
\index{{\tt \bfseries wiener\_lpdf }!{\tt (reals y \textbar\ reals alpha, reals tau, reals beta, reals delta): real}|hyperpage}

`real` **`wiener_lpdf`**`(reals y | reals alpha, reals tau, reals beta, reals delta)`<br>\newline
The log of the Wiener first passage time density of y given boundary
separation alpha, non-decision time tau, a-priori bias beta and drift
rate delta

<!-- real; wiener_lupdf; (reals y | reals alpha, reals tau, reals beta, reals delta); -->
\index{{\tt \bfseries wiener\_lupdf }!{\tt (reals y \textbar\ reals alpha, reals tau, reals beta, reals delta): real}|hyperpage}

`real` **`wiener_lupdf`**`(reals y | reals alpha, reals tau, reals beta, reals delta)`<br>\newline
The log of the Wiener first passage time density of y given boundary
separation alpha, non-decision time tau, a-priori bias beta and drift
rate delta dropping constant additive terms

### boundaries

Stan returns the first passage time of the accumulation process over
the upper boundary only. To get the result for the lower boundary, use
\[ \text{wiener}(y | \alpha, \tau, 1 - \beta, - \delta) \] For more
details, see the appendix of @Vandekerckhove-Wabersich:2014.
