# Positive Continuous Distributions

The positive continuous probability functions have support on the
positive real numbers.

```{r results='asis', echo=FALSE}
if (knitr::is_html_output()) {
cat(' * <a href="lognormal.html">Lognormal Distribution</a>\n')
cat(' * <a href="chi-square-distribution.html">Chi-Square Distribution</a>\n')
cat(' * <a href="inverse-chi-square-distribution.html">Inverse Chi-Square Distribution</a>\n')
cat(' * <a href="scaled-inverse-chi-square-distribution.html">Scaled Inverse Chi-Square Distribution</a>\n')
cat(' * <a href="exponential-distribution.html">Exponential Distribution</a>\n')
cat(' * <a href="gamma-distribution.html">Gamma Distribution</a>\n')
cat(' * <a href="inverse-gamma-distribution.html">Inverse Gamma Distribution</a>\n')
cat(' * <a href="weibull-distribution.html">Weibull Distribution</a>\n')
cat(' * <a href="frechet-distribution.html">Frechet Distribution</a>\n')
cat(' * <a href="rayleigh-distribution.html">Rayleigh Distribution</a>\n')
}
```

## Lognormal distribution {#lognormal}

### Probability density function

If $\mu \in \mathbb{R}$ and $\sigma \in \mathbb{R}^+$, then for $y \in
\mathbb{R}^+$, \[ \text{LogNormal}(y|\mu,\sigma) = \frac{1}{\sqrt{2
\pi} \ \sigma} \, \frac{1}{y} \ \exp \! \left(        - \, \frac{1}{2}
\, \left( \frac{\log y - \mu}{\sigma} \right)^2      \right) . \]

### Sampling statement

`y ~ ` **`lognormal`**`(mu, sigma)`

Increment target log probability density with `lognormal_lupdf(y | mu, sigma)`.
`r since("2.0")`
<!-- real; lognormal ~; -->
\index{{\tt \bfseries lognormal }!sampling statement|hyperpage}

### Stan functions

<!-- real; lognormal_lpdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries lognormal\_lpdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`lognormal_lpdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the lognormal density of y given location mu and scale
sigma
`r since("2.12")`

<!-- real; lognormal_lupdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries lognormal\_lupdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`lognormal_lupdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the lognormal density of y given location mu and scale
sigma dropping constant additive terms
`r since("2.25")`

<!-- real; lognormal_cdf; (reals y, reals mu, reals sigma); -->
\index{{\tt \bfseries lognormal\_cdf }!{\tt (reals y, reals mu, reals sigma): real}|hyperpage}

`real` **`lognormal_cdf`**`(reals y, reals mu, reals sigma)`<br>\newline
The cumulative lognormal distribution function of y given location mu
and scale sigma
`r since("2.0")`

<!-- real; lognormal_lcdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries lognormal\_lcdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`lognormal_lcdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the lognormal cumulative distribution function of y given
location mu and scale sigma
`r since("2.12")`

<!-- real; lognormal_lccdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries lognormal\_lccdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`lognormal_lccdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the lognormal complementary cumulative distribution
function of y given location mu and scale sigma
`r since("2.12")`

<!-- R; lognormal_rng; (reals mu, reals sigma); -->
\index{{\tt \bfseries lognormal\_rng }!{\tt (reals mu, reals sigma): R}|hyperpage}

`R` **`lognormal_rng`**`(reals mu, reals sigma)`<br>\newline
Generate a lognormal variate with location mu and scale sigma; may
only be used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.22")`

## Chi-square distribution

### Probability density function

If $\nu \in \mathbb{R}^+$, then for $y \in \mathbb{R}^+$, \[
\text{ChiSquare}(y|\nu) = \frac{2^{-\nu/2}}     {\Gamma(\nu / 2)} \,
y^{\nu/2 - 1} \, \exp \! \left( -\, \frac{1}{2} \, y \right) . \]

### Sampling statement

`y ~ ` **`chi_square`**`(nu)`

Increment target log probability density with `chi_square_lupdf(y | nu)`.
`r since("2.0")`
<!-- real; chi_square ~; -->
\index{{\tt \bfseries chi\_square }!sampling statement|hyperpage}

### Stan functions

<!-- real; chi_square_lpdf; (reals y | reals nu); -->
\index{{\tt \bfseries chi\_square\_lpdf }!{\tt (reals y \textbar\ reals nu): real}|hyperpage}

`real` **`chi_square_lpdf`**`(reals y | reals nu)`<br>\newline
The log of the Chi-square density of y given degrees of freedom nu
`r since("2.12")`

<!-- real; chi_square_lupdf; (reals y | reals nu); -->
\index{{\tt \bfseries chi\_square\_lupdf }!{\tt (reals y \textbar\ reals nu): real}|hyperpage}

`real` **`chi_square_lupdf`**`(reals y | reals nu)`<br>\newline
The log of the Chi-square density of y given degrees of freedom nu
dropping constant additive terms
`r since("2.25")`

<!-- real; chi_square_cdf; (reals y, reals nu); -->
\index{{\tt \bfseries chi\_square\_cdf }!{\tt (reals y, reals nu): real}|hyperpage}

`real` **`chi_square_cdf`**`(reals y, reals nu)`<br>\newline
The Chi-square cumulative distribution function of y given degrees of
freedom nu
`r since("2.0")`

<!-- real; chi_square_lcdf; (reals y | reals nu); -->
\index{{\tt \bfseries chi\_square\_lcdf }!{\tt (reals y \textbar\ reals nu): real}|hyperpage}

`real` **`chi_square_lcdf`**`(reals y | reals nu)`<br>\newline
The log of the Chi-square cumulative distribution function of y given
degrees of freedom nu
`r since("2.12")`

<!-- real; chi_square_lccdf; (reals y | reals nu); -->
\index{{\tt \bfseries chi\_square\_lccdf }!{\tt (reals y \textbar\ reals nu): real}|hyperpage}

`real` **`chi_square_lccdf`**`(reals y | reals nu)`<br>\newline
The log of the complementary Chi-square cumulative distribution
function of y given degrees of freedom nu
`r since("2.12")`

<!-- R; chi_square_rng; (reals nu); -->
\index{{\tt \bfseries chi\_square\_rng }!{\tt (reals nu): R}|hyperpage}

`R` **`chi_square_rng`**`(reals nu)`<br>\newline
Generate a Chi-square variate with degrees of freedom nu; may only be
used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Inverse chi-square distribution

### Probability density function

If $\nu \in \mathbb{R}^+$, then for $y \in \mathbb{R}^+$, \[
\text{InvChiSquare}(y \, | \, \nu) = \frac{2^{-\nu/2}}    {\Gamma(\nu
/ 2)} \, y^{-\nu/2 - 1} \, \exp\! \left( \! - \, \frac{1}{2} \,
\frac{1}{y} \right) . \]

### Sampling statement

`y ~ ` **`inv_chi_square`**`(nu)`

Increment target log probability density with `inv_chi_square_lupdf(y | nu)`.
`r since("2.0")`
<!-- real; inv_chi_square ~; -->
\index{{\tt \bfseries inv\_chi\_square }!sampling statement|hyperpage}

### Stan functions

<!-- real; inv_chi_square_lpdf; (reals y | reals nu); -->
\index{{\tt \bfseries inv\_chi\_square\_lpdf }!{\tt (reals y \textbar\ reals nu): real}|hyperpage}

`real` **`inv_chi_square_lpdf`**`(reals y | reals nu)`<br>\newline
The log of the inverse Chi-square density of y given degrees of
freedom nu
`r since("2.12")`

<!-- real; inv_chi_square_lupdf; (reals y | reals nu); -->
\index{{\tt \bfseries inv\_chi\_square\_lupdf }!{\tt (reals y \textbar\ reals nu): real}|hyperpage}

`real` **`inv_chi_square_lupdf`**`(reals y | reals nu)`<br>\newline
The log of the inverse Chi-square density of y given degrees of
freedom nu dropping constant additive terms
`r since("2.25")`

<!-- real; inv_chi_square_cdf; (reals y, reals nu); -->
\index{{\tt \bfseries inv\_chi\_square\_cdf }!{\tt (reals y, reals nu): real}|hyperpage}

`real` **`inv_chi_square_cdf`**`(reals y, reals nu)`<br>\newline
The inverse Chi-squared cumulative distribution function of y given
degrees of freedom nu
`r since("2.0")`

<!-- real; inv_chi_square_lcdf; (reals y | reals nu); -->
\index{{\tt \bfseries inv\_chi\_square\_lcdf }!{\tt (reals y \textbar\ reals nu): real}|hyperpage}

`real` **`inv_chi_square_lcdf`**`(reals y | reals nu)`<br>\newline
The log of the inverse Chi-squared cumulative distribution function of
y given degrees of freedom nu
`r since("2.12")`

<!-- real; inv_chi_square_lccdf; (reals y | reals nu); -->
\index{{\tt \bfseries inv\_chi\_square\_lccdf }!{\tt (reals y \textbar\ reals nu): real}|hyperpage}

`real` **`inv_chi_square_lccdf`**`(reals y | reals nu)`<br>\newline
The log of the inverse Chi-squared complementary cumulative
distribution function of y given degrees of freedom nu
`r since("2.12")`

<!-- R; inv_chi_square_rng; (reals nu); -->
\index{{\tt \bfseries inv\_chi\_square\_rng }!{\tt (reals nu): R}|hyperpage}

`R` **`inv_chi_square_rng`**`(reals nu)`<br>\newline
Generate an inverse Chi-squared variate with degrees of freedom nu;
may only be used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Scaled inverse chi-square distribution

### Probability density function

If $\nu \in \mathbb{R}^+$ and $\sigma \in \mathbb{R}^+$, then for $y
\in \mathbb{R}^+$, \[ \text{ScaledInvChiSquare}(y|\nu,\sigma) =
\frac{(\nu / 2)^{\nu/2}}      {\Gamma(\nu / 2)} \, \sigma^{\nu} \,
y^{-(\nu/2 + 1)} \, \exp \! \left( \!    - \, \frac{1}{2} \, \nu \,
\sigma^2 \, \frac{1}{y} \right) . \]

### Sampling statement

`y ~ ` **`scaled_inv_chi_square`**`(nu, sigma)`

Increment target log probability density with `scaled_inv_chi_square_lupdf(y | nu, sigma)`.
`r since("2.0")`
<!-- real; scaled_inv_chi_square ~; -->
\index{{\tt \bfseries scaled\_inv\_chi\_square }!sampling statement|hyperpage}

### Stan functions

<!-- real; scaled_inv_chi_square_lpdf; (reals y | reals nu, reals sigma); -->
\index{{\tt \bfseries scaled\_inv\_chi\_square\_lpdf }!{\tt (reals y \textbar\ reals nu, reals sigma): real}|hyperpage}

`real` **`scaled_inv_chi_square_lpdf`**`(reals y | reals nu, reals sigma)`<br>\newline
The log of the scaled inverse Chi-square density of y given degrees of
freedom nu and scale sigma
`r since("2.12")`

<!-- real; scaled_inv_chi_square_lupdf; (reals y | reals nu, reals sigma); -->
\index{{\tt \bfseries scaled\_inv\_chi\_square\_lupdf }!{\tt (reals y \textbar\ reals nu, reals sigma): real}|hyperpage}

`real` **`scaled_inv_chi_square_lupdf`**`(reals y | reals nu, reals sigma)`<br>\newline
The log of the scaled inverse Chi-square density of y given degrees of
freedom nu and scale sigma dropping constant additive terms
`r since("2.25")`

<!-- real; scaled_inv_chi_square_cdf; (reals y, reals nu, reals sigma); -->
\index{{\tt \bfseries scaled\_inv\_chi\_square\_cdf }!{\tt (reals y, reals nu, reals sigma): real}|hyperpage}

`real` **`scaled_inv_chi_square_cdf`**`(reals y, reals nu, reals sigma)`<br>\newline
The scaled inverse Chi-square cumulative distribution function of y
given degrees of freedom nu and scale sigma
`r since("2.0")`

<!-- real; scaled_inv_chi_square_lcdf; (reals y | reals nu, reals sigma); -->
\index{{\tt \bfseries scaled\_inv\_chi\_square\_lcdf }!{\tt (reals y \textbar\ reals nu, reals sigma): real}|hyperpage}

`real` **`scaled_inv_chi_square_lcdf`**`(reals y | reals nu, reals sigma)`<br>\newline
The log of the scaled inverse Chi-square cumulative distribution
function of y given degrees of freedom nu and scale sigma
`r since("2.12")`

<!-- real; scaled_inv_chi_square_lccdf; (reals y | reals nu, reals sigma); -->
\index{{\tt \bfseries scaled\_inv\_chi\_square\_lccdf }!{\tt (reals y \textbar\ reals nu, reals sigma): real}|hyperpage}

`real` **`scaled_inv_chi_square_lccdf`**`(reals y | reals nu, reals sigma)`<br>\newline
The log of the scaled inverse Chi-square complementary cumulative
distribution function of y given degrees of freedom nu and scale sigma
`r since("2.12")`

<!-- R; scaled_inv_chi_square_rng; (reals nu, reals sigma); -->
\index{{\tt \bfseries scaled\_inv\_chi\_square\_rng }!{\tt (reals nu, reals sigma): R}|hyperpage}

`R` **`scaled_inv_chi_square_rng`**`(reals nu, reals sigma)`<br>\newline
Generate a scaled inverse Chi-squared variate with degrees of freedom
nu and scale sigma; may only be used in transformed data and generated
quantities blocks. For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Exponential distribution {#exponential-distribution}

### Probability density function

If $\beta \in \mathbb{R}^+$, then for $y \in \mathbb{R}^+$, \[
\text{Exponential}(y|\beta) = \beta \, \exp ( - \beta \, y ) . \]

### Sampling statement

`y ~ ` **`exponential`**`(beta)`

Increment target log probability density with `exponential_lupdf(y | beta)`.
`r since("2.0")`
<!-- real; exponential ~; -->
\index{{\tt \bfseries exponential }!sampling statement|hyperpage}

### Stan functions

<!-- real; exponential_lpdf; (reals y | reals beta); -->
\index{{\tt \bfseries exponential\_lpdf }!{\tt (reals y \textbar\ reals beta): real}|hyperpage}

`real` **`exponential_lpdf`**`(reals y | reals beta)`<br>\newline
The log of the exponential density of y given inverse scale beta
`r since("2.12")`

<!-- real; exponential_lupdf; (reals y | reals beta); -->
\index{{\tt \bfseries exponential\_lupdf }!{\tt (reals y \textbar\ reals beta): real}|hyperpage}

`real` **`exponential_lupdf`**`(reals y | reals beta)`<br>\newline
The log of the exponential density of y given inverse scale beta
dropping constant additive terms
`r since("2.25")`

<!-- real; exponential_cdf; (reals y, reals beta); -->
\index{{\tt \bfseries exponential\_cdf }!{\tt (reals y, reals beta): real}|hyperpage}

`real` **`exponential_cdf`**`(reals y, reals beta)`<br>\newline
The exponential cumulative distribution function of y given inverse
scale beta
`r since("2.0")`

<!-- real; exponential_lcdf; (reals y | reals beta); -->
\index{{\tt \bfseries exponential\_lcdf }!{\tt (reals y \textbar\ reals beta): real}|hyperpage}

`real` **`exponential_lcdf`**`(reals y | reals beta)`<br>\newline
The log of the exponential cumulative distribution function of y given
inverse scale beta
`r since("2.12")`

<!-- real; exponential_lccdf; (reals y | reals beta); -->
\index{{\tt \bfseries exponential\_lccdf }!{\tt (reals y \textbar\ reals beta): real}|hyperpage}

`real` **`exponential_lccdf`**`(reals y | reals beta)`<br>\newline
The log of the exponential complementary cumulative distribution
function of y given inverse scale beta
`r since("2.12")`

<!-- R; exponential_rng; (reals beta); -->
\index{{\tt \bfseries exponential\_rng }!{\tt (reals beta): R}|hyperpage}

`R` **`exponential_rng`**`(reals beta)`<br>\newline
Generate an exponential variate with inverse scale beta; may only be
used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Gamma distribution

### Probability density function

If $\alpha \in \mathbb{R}^+$ and $\beta \in \mathbb{R}^+$, then for $y
\in \mathbb{R}^+$, \[ \text{Gamma}(y|\alpha,\beta) =
\frac{\beta^{\alpha}}      {\Gamma(\alpha)} \, y^{\alpha - 1}
\exp(-\beta \, y) . \]

### Sampling statement

`y ~ ` **`gamma`**`(alpha, beta)`

Increment target log probability density with `gamma_lupdf(y | alpha, beta)`.
`r since("2.0")`
<!-- real; gamma ~; -->
\index{{\tt \bfseries gamma }!sampling statement|hyperpage}

### Stan functions

<!-- real; gamma_lpdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries gamma\_lpdf }!{\tt (reals y \textbar\ reals alpha, reals beta): real}|hyperpage}

`real` **`gamma_lpdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the gamma density of y given shape alpha and inverse scale
beta
`r since("2.12")`

<!-- real; gamma_lupdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries gamma\_lupdf }!{\tt (reals y \textbar\ reals alpha, reals beta): real}|hyperpage}

`real` **`gamma_lupdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the gamma density of y given shape alpha and inverse scale
beta dropping constant additive terms
`r since("2.25")`

<!-- real; gamma_cdf; (reals y, reals alpha, reals beta); -->
\index{{\tt \bfseries gamma\_cdf }!{\tt (reals y, reals alpha, reals beta): real}|hyperpage}

`real` **`gamma_cdf`**`(reals y, reals alpha, reals beta)`<br>\newline
The cumulative gamma distribution function of y given shape alpha and
inverse scale beta
`r since("2.0")`

<!-- real; gamma_lcdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries gamma\_lcdf }!{\tt (reals y \textbar\ reals alpha, reals beta): real}|hyperpage}

`real` **`gamma_lcdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the cumulative gamma distribution function of y given shape
alpha and inverse scale beta
`r since("2.12")`

<!-- real; gamma_lccdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries gamma\_lccdf }!{\tt (reals y \textbar\ reals alpha, reals beta): real}|hyperpage}

`real` **`gamma_lccdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the complementary cumulative gamma distribution function of
y given shape alpha and inverse scale beta
`r since("2.12")`

<!-- R; gamma_rng; (reals alpha, reals beta); -->
\index{{\tt \bfseries gamma\_rng }!{\tt (reals alpha, reals beta): R}|hyperpage}

`R` **`gamma_rng`**`(reals alpha, reals beta)`<br>\newline
Generate a gamma variate with shape alpha and inverse scale beta; may
only be used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Inverse gamma Distribution

### Probability density function

If $\alpha \in \mathbb{R}^+$ and $\beta \in \mathbb{R}^+$, then for $y
\in \mathbb{R}^+$, \[ \text{InvGamma}(y|\alpha,\beta) =
\frac{\beta^{\alpha}}      {\Gamma(\alpha)} \ y^{-(\alpha + 1)} \,
\exp \! \left( \! - \beta \, \frac{1}{y} \right) . \]

### Sampling statement

`y ~ ` **`inv_gamma`**`(alpha, beta)`

Increment target log probability density with `inv_gamma_lupdf(y | alpha, beta)`.
`r since("2.0")`
<!-- real; inv_gamma ~; -->
\index{{\tt \bfseries inv\_gamma }!sampling statement|hyperpage}

### Stan functions

<!-- real; inv_gamma_lpdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries inv\_gamma\_lpdf }!{\tt (reals y \textbar\ reals alpha, reals beta): real}|hyperpage}

`real` **`inv_gamma_lpdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the inverse gamma density of y given shape alpha and scale
beta
`r since("2.12")`

<!-- real; inv_gamma_lupdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries inv\_gamma\_lupdf }!{\tt (reals y \textbar\ reals alpha, reals beta): real}|hyperpage}

`real` **`inv_gamma_lupdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the inverse gamma density of y given shape alpha and scale
beta dropping constant additive terms
`r since("2.25")`

<!-- real; inv_gamma_cdf; (reals y, reals alpha, reals beta); -->
\index{{\tt \bfseries inv\_gamma\_cdf }!{\tt (reals y, reals alpha, reals beta): real}|hyperpage}

`real` **`inv_gamma_cdf`**`(reals y, reals alpha, reals beta)`<br>\newline
The inverse gamma cumulative distribution function of y given shape
alpha and scale beta
`r since("2.0")`

<!-- real; inv_gamma_lcdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries inv\_gamma\_lcdf }!{\tt (reals y \textbar\ reals alpha, reals beta): real}|hyperpage}

`real` **`inv_gamma_lcdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the inverse gamma cumulative distribution function of y
given shape alpha and scale beta
`r since("2.12")`

<!-- real; inv_gamma_lccdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries inv\_gamma\_lccdf }!{\tt (reals y \textbar\ reals alpha, reals beta): real}|hyperpage}

`real` **`inv_gamma_lccdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the inverse gamma complementary cumulative distribution
function of y given shape alpha and scale beta
`r since("2.12")`

<!-- R; inv_gamma_rng; (reals alpha, reals beta); -->
\index{{\tt \bfseries inv\_gamma\_rng }!{\tt (reals alpha, reals beta): R}|hyperpage}

`R` **`inv_gamma_rng`**`(reals alpha, reals beta)`<br>\newline
Generate an inverse gamma variate with shape alpha and scale beta; may
only be used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Weibull distribution

### Probability density function

If $\alpha \in \mathbb{R}^+$ and $\sigma \in \mathbb{R}^+$, then for
$y \in [0,\infty)$, \[ \text{Weibull}(y|\alpha,\sigma) =
\frac{\alpha}{\sigma} \, \left( \frac{y}{\sigma} \right)^{\alpha - 1}
\, \exp \! \left( \! - \left( \frac{y}{\sigma} \right)^{\alpha}
\right) . \]

Note that if $Y \propto \text{Weibull}(\alpha,\sigma)$, then $Y^{-1}
\propto \text{Frechet}(\alpha,\sigma^{-1})$.

### Sampling statement

`y ~ ` **`weibull`**`(alpha, sigma)`

Increment target log probability density with `weibull_lupdf(y | alpha, sigma)`.
`r since("2.0")`
<!-- real; weibull ~; -->
\index{{\tt \bfseries weibull }!sampling statement|hyperpage}

### Stan functions

<!-- real; weibull_lpdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries weibull\_lpdf }!{\tt (reals y \textbar\ reals alpha, reals sigma): real}|hyperpage}

`real` **`weibull_lpdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Weibull density of y given shape alpha and scale sigma
`r since("2.12")`

<!-- real; weibull_lupdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries weibull\_lupdf }!{\tt (reals y \textbar\ reals alpha, reals sigma): real}|hyperpage}

`real` **`weibull_lupdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Weibull density of y given shape alpha and scale sigma
dropping constant additive terms
`r since("2.25")`

<!-- real; weibull_cdf; (reals y, reals alpha, reals sigma); -->
\index{{\tt \bfseries weibull\_cdf }!{\tt (reals y, reals alpha, reals sigma): real}|hyperpage}

`real` **`weibull_cdf`**`(reals y, reals alpha, reals sigma)`<br>\newline
The Weibull cumulative distribution function of y given shape alpha
and scale sigma
`r since("2.0")`

<!-- real; weibull_lcdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries weibull\_lcdf }!{\tt (reals y \textbar\ reals alpha, reals sigma): real}|hyperpage}

`real` **`weibull_lcdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Weibull cumulative distribution function of y given
shape alpha and scale sigma
`r since("2.12")`

<!-- real; weibull_lccdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries weibull\_lccdf }!{\tt (reals y \textbar\ reals alpha, reals sigma): real}|hyperpage}

`real` **`weibull_lccdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Weibull complementary cumulative distribution function
of y given shape alpha and scale sigma
`r since("2.12")`

<!-- R; weibull_rng; (reals alpha, reals sigma); -->
\index{{\tt \bfseries weibull\_rng }!{\tt (reals alpha, reals sigma): R}|hyperpage}

`R` **`weibull_rng`**`(reals alpha, reals sigma)`<br>\newline
Generate a weibull variate with shape alpha and scale sigma; may only
be used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Frechet distribution

### Probability density function

If $\alpha \in \mathbb{R}^+$ and $\sigma \in \mathbb{R}^+$, then for
$y \in \mathbb{R}^+$, \[ \text{Frechet}(y|\alpha,\sigma) =
\frac{\alpha}{\sigma} \, \left( \frac{y}{\sigma} \right)^{-\alpha - 1}
\, \exp \! \left( \! - \left( \frac{y}{\sigma} \right)^{-\alpha}
\right) . \]

Note that if $Y \propto \text{Frechet}(\alpha,\sigma)$, then $Y^{-1}
\propto \text{Weibull}(\alpha,\sigma^{-1})$.

### Sampling statement

`y ~ ` **`frechet`**`(alpha, sigma)`

Increment target log probability density with `frechet_lupdf(y | alpha, sigma)`.
`r since("2.5")`
<!-- real; frechet ~; -->
\index{{\tt \bfseries frechet }!sampling statement|hyperpage}

### Stan functions

<!-- real; frechet_lpdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries frechet\_lpdf }!{\tt (reals y \textbar\ reals alpha, reals sigma): real}|hyperpage}

`real` **`frechet_lpdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Frechet density of y given shape alpha and scale sigma
`r since("2.12")`

<!-- real; frechet_lupdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries frechet\_lupdf }!{\tt (reals y \textbar\ reals alpha, reals sigma): real}|hyperpage}

`real` **`frechet_lupdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Frechet density of y given shape alpha and scale sigma
dropping constant additive terms
`r since("2.25")`

<!-- real; frechet_cdf; (reals y, reals alpha, reals sigma); -->
\index{{\tt \bfseries frechet\_cdf }!{\tt (reals y, reals alpha, reals sigma): real}|hyperpage}

`real` **`frechet_cdf`**`(reals y, reals alpha, reals sigma)`<br>\newline
The Frechet cumulative distribution function of y given shape alpha
and scale sigma
`r since("2.5")`

<!-- real; frechet_lcdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries frechet\_lcdf }!{\tt (reals y \textbar\ reals alpha, reals sigma): real}|hyperpage}

`real` **`frechet_lcdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Frechet cumulative distribution function of y given
shape alpha and scale sigma
`r since("2.12")`

<!-- real; frechet_lccdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries frechet\_lccdf }!{\tt (reals y \textbar\ reals alpha, reals sigma): real}|hyperpage}

`real` **`frechet_lccdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Frechet complementary cumulative distribution function
of y given shape alpha and scale sigma
`r since("2.12")`

<!-- R; frechet_rng; (reals alpha, reals sigma); -->
\index{{\tt \bfseries frechet\_rng }!{\tt (reals alpha, reals sigma): R}|hyperpage}

`R` **`frechet_rng`**`(reals alpha, reals sigma)`<br>\newline
Generate a Frechet variate with shape alpha and scale sigma; may only
be used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Rayleigh distribution

### Probability density function

If $\sigma \in \mathbb{R}^+$, then for $y \in [0,\infty)$, \[
\text{Rayleigh}(y|\sigma) = \frac{y}{\sigma^2} \exp(-y^2 / 2\sigma^2)
\!. \]

### Sampling statement

`y ~ ` **`rayleigh`**`(sigma)`

Increment target log probability density with `rayleigh_lupdf(y | sigma)`.
`r since("2.0")`
<!-- real; rayleigh ~; -->
\index{{\tt \bfseries rayleigh }!sampling statement|hyperpage}

### Stan functions

<!-- real; rayleigh_lpdf; (reals y | reals sigma); -->
\index{{\tt \bfseries rayleigh\_lpdf }!{\tt (reals y \textbar\ reals sigma): real}|hyperpage}

`real` **`rayleigh_lpdf`**`(reals y | reals sigma)`<br>\newline
The log of the Rayleigh density of y given scale sigma
`r since("2.12")`

<!-- real; rayleigh_lupdf; (reals y | reals sigma); -->
\index{{\tt \bfseries rayleigh\_lupdf }!{\tt (reals y \textbar\ reals sigma): real}|hyperpage}

`real` **`rayleigh_lupdf`**`(reals y | reals sigma)`<br>\newline
The log of the Rayleigh density of y given scale sigma
dropping constant additive terms
`r since("2.25")`

<!-- real; rayleigh_cdf; (real y, real sigma); -->
\index{{\tt \bfseries rayleigh\_cdf }!{\tt (real y, real sigma): real}|hyperpage}

`real` **`rayleigh_cdf`**`(real y, real sigma)`<br>\newline
The Rayleigh cumulative distribution of y given scale sigma
`r since("2.0")`

<!-- real; rayleigh_lcdf; (real y | real sigma); -->
\index{{\tt \bfseries rayleigh\_lcdf }!{\tt (real y \textbar\ real sigma): real}|hyperpage}

`real` **`rayleigh_lcdf`**`(real y | real sigma)`<br>\newline
The log of the Rayleigh cumulative distribution of y given scale sigma
`r since("2.12")`

<!-- real; rayleigh_lccdf; (real y | real sigma); -->
\index{{\tt \bfseries rayleigh\_lccdf }!{\tt (real y \textbar\ real sigma): real}|hyperpage}

`real` **`rayleigh_lccdf`**`(real y | real sigma)`<br>\newline
The log of the Rayleigh complementary cumulative distribution of y
given scale sigma
`r since("2.12")`

<!-- R; rayleigh_rng; (reals sigma); -->
\index{{\tt \bfseries rayleigh\_rng }!{\tt (reals sigma): R}|hyperpage}

`R` **`rayleigh_rng`**`(reals sigma)`<br>\newline
Generate a Rayleigh variate with scale sigma; may only be used in
generated quantities block. For a description of argument and return
types, see section [vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`


## Log-logistic distribution

### Probability density function

If $\alpha, \beta \in \mathbb{R}^+$, then for $y \in
\mathbb{R}^+$, \[ \text{Log-Logistic}(y|\alpha,\beta) = \frac{\
\left(\frac{\beta}{\alpha}\right) \left(\frac{x}{\alpha}\right)^{\beta-1}\
}{\left(1 + \left(\frac{x}{\alpha}\right)^\beta\right)^2} . \]

### Sampling statement

`y ~ ` **`loglogistic`**`(mu, sigma)`

Increment target log probability density with `loglogistic_lupdf(y | mu, sigma)`.
`r since("2.29")`
<!-- real; loglogistic ~; -->
\index{{\tt \bfseries loglogistic }!sampling statement|hyperpage}

### Stan functions

<!-- real; loglogistic_lpdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries loglogistic\_lpdf }!{\tt (reals y \textbar\ reals alpha, reals beta): real}|hyperpage}

`real` **`loglogistic_lpdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the log-logistic density of y given shape parameters alpha and beta
`r since("2.29")`

<!-- real; loglogistic_cdf; (reals y, reals alpha, reals beta); -->
\index{{\tt \bfseries loglogistic\_cdf }!{\tt (reals y, reals alpha, reals beta): real}|hyperpage}

`real` **`loglogistic_cdf`**`(reals y, reals alpha, reals beta)`<br>\newline
The log-logistic cumulative distribution function of y given shape parameters alpha and beta
`r since("2.29")`

<!-- R; loglogistic_rng; (reals mu, reals sigma); -->
\index{{\tt \bfseries loglogistic\_rng}!{\tt (reals alpha, reals beta): R}|hyperpage}

`R` **`loglogistic_rng`**`(reals alpha, reals beta)`<br>\newline
Generate a log-logistic variate with shape parameters alpha and beta; may only
be used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.29")`
