# Unbounded Discrete Distributions

The unbounded discrete distributions have support over the natural
numbers (i.e., the non-negative integers).

```{r results='asis', echo=FALSE}
if (knitr::is_html_output()) {
cat(' * <a href="negative-binomial-distribution.html">Negative Binomial Distribution</a>\n')
cat(' * <a href="nbalt.html">Negative Binomial Distribution (alternative parameterization)</a>\n')
cat(' * <a href="neg-binom-2-log.html">Negative Binomial Distribution (log alternative parameterization)</a>\n')
cat(' * <a href="neg-binom-2-log-glm.html">Negative-Binomial-2-Log generalized Linear Model (Negative Binomial Regression)</a>\n')
cat(' * <a href="poisson.html">Poisson Distribution</a>\n')
cat(' * <a href="poisson-distribution-log-parameterization.html">Poisson Distribution, Log Parameterization</a>\n')
cat(' * <a href="poisson-log-glm.html">Poisson-Log generalized Linear Model (Poisson Regression)</a>\n')
cat(' * <a href="poisson-binomial.html">Poisson-binomial Distribution</a>\n')
}
```

## Negative binomial distribution

For the negative binomial distribution Stan uses the parameterization
described in @GelmanEtAl:2013.  For alternative parameterizations, see
section [negative binomial glm](#neg-binom-2-log).

### Probability mass function

If $\alpha \in \mathbb{R}^+$ and $\beta \in \mathbb{R}^+$, then for $n
\in \mathbb{N}$, \[ \text{NegBinomial}(n~|~\alpha,\beta) = \binom{n +
\alpha - 1}{\alpha - 1} \, \left( \frac{\beta}{\beta+1}
\right)^{\!\alpha} \, \left( \frac{1}{\beta + 1} \right)^{\!n} \!. \]

The mean and variance of a random variable $n \sim
\text{NegBinomial}(\alpha,\beta)$ are given by \[ \mathbb{E}[n] =
\frac{\alpha}{\beta} \ \ \text{ and } \ \ \text{Var}[n] =
\frac{\alpha}{\beta^2} (\beta + 1). \]

### Sampling statement

`n ~ ` **`neg_binomial`**`(alpha, beta)`

Increment target log probability density with `neg_binomial_lupmf(n | alpha, beta)`.
<!-- real; neg_binomial ~; -->
\index{{\tt \bfseries neg\_binomial }!sampling statement|hyperpage}

### Stan functions

<!-- real; neg_binomial_lpmf; (ints n | reals alpha, reals beta); -->
\index{{\tt \bfseries neg\_binomial\_lpmf }!{\tt (ints n \textbar\ reals alpha, reals beta): real}|hyperpage}

`real` **`neg_binomial_lpmf`**`(ints n | reals alpha, reals beta)`<br>\newline
The log negative binomial probability mass of `n` given shape `alpha` and
inverse scale `beta`

<!-- real; neg_binomial_lupmf; (ints n | reals alpha, reals beta); -->
\index{{\tt \bfseries neg\_binomial\_lupmf }!{\tt (ints n \textbar\ reals alpha, reals beta): real}|hyperpage}

`real` **`neg_binomial_lupmf`**`(ints n | reals alpha, reals beta)`<br>\newline
The log negative binomial probability mass of `n` given shape `alpha` and
inverse scale `beta` dropping constant additive terms

<!-- real; neg_binomial_cdf; (ints n, reals alpha, reals beta); -->
\index{{\tt \bfseries neg\_binomial\_cdf }!{\tt (ints n, reals alpha, reals beta): real}|hyperpage}

`real` **`neg_binomial_cdf`**`(ints n, reals alpha, reals beta)`<br>\newline
The negative binomial cumulative distribution function of `n` given
shape `alpha` and inverse scale `beta`

<!-- real; neg_binomial_lcdf; (ints n | reals alpha, reals beta); -->
\index{{\tt \bfseries neg\_binomial\_lcdf }!{\tt (ints n \textbar\ reals alpha, reals beta): real}|hyperpage}

`real` **`neg_binomial_lcdf`**`(ints n | reals alpha, reals beta)`<br>\newline
The log of the negative binomial cumulative distribution function of `n`
given shape `alpha` and inverse scale `beta`

<!-- real; neg_binomial_lccdf; (ints n | reals alpha, reals beta); -->
\index{{\tt \bfseries neg\_binomial\_lccdf }!{\tt (ints n \textbar\ reals alpha, reals beta): real}|hyperpage}

`real` **`neg_binomial_lccdf`**`(ints n | reals alpha, reals beta)`<br>\newline
The log of the negative binomial complementary cumulative distribution
function of `n` given shape `alpha` and inverse scale `beta`

<!-- R; neg_binomial_rng; (reals alpha, reals beta); -->
\index{{\tt \bfseries neg\_binomial\_rng }!{\tt (reals alpha, reals beta): R}|hyperpage}

`R` **`neg_binomial_rng`**`(reals alpha, reals beta)`<br>\newline
Generate a negative binomial variate with shape `alpha` and inverse
scale `beta`; may only be used in transformed data and generated quantities blocks.
`alpha` $/$ `beta` must be less than $2 ^ {29}$. For a description of argument and
return types, see section [vectorized function signatures](#prob-vectorization).

## Negative binomial distribution (alternative parameterization) {#nbalt}

Stan also provides an alternative parameterization of the negative
binomial distribution directly using a mean (i.e., location) parameter
and a parameter that controls overdispersion relative to the square of
the mean.  Section [combinatorial functions](#betafun), below, provides a second
alternative parameterization directly in terms of the log mean.

### Probability mass function

The first parameterization is for $\mu \in \mathbb{R}^+$ and $\phi \in
\mathbb{R}^+$, which for $n \in \mathbb{N}$ is defined as \[
\text{NegBinomial2}(n \, | \, \mu, \phi)  = \binom{n + \phi - 1}{n} \,
\left( \frac{\mu}{\mu+\phi} \right)^{\!n} \, \left(
\frac{\phi}{\mu+\phi} \right)^{\!\phi} \!. \]

The mean and variance of a random variable $n \sim
\text{NegBinomial2}(n~|~\mu,\phi)$ are \[ \mathbb{E}[n] = \mu \ \ \
\text{ and } \ \ \ \text{Var}[n] = \mu + \frac{\mu^2}{\phi}. \] Recall
that $\text{Poisson}(\mu)$ has variance $\mu$, so $\mu^2 / \phi > 0$
is the additional variance of the negative binomial above that of the
Poisson with mean $\mu$.  So the inverse of parameter $\phi$ controls
the overdispersion, scaled by the square of the mean, $\mu^2$.

### Sampling statement

`n ~ ` **`neg_binomial_2`**`(mu, phi)`

Increment target log probability density with `neg_binomial_2_lupmf(n | mu, phi)`.
<!-- real; neg_binomial_2 ~; -->
\index{{\tt \bfseries neg\_binomial\_2 }!sampling statement|hyperpage}

### Stan functions

<!-- real; neg_binomial_2_lpmf; (ints n | reals mu, reals phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_lpmf }!{\tt (ints n \textbar\ reals mu, reals phi): real}|hyperpage}

`real` **`neg_binomial_2_lpmf`**`(ints n | reals mu, reals phi)`<br>\newline
The negative binomial probability mass of `n` given location `mu` and
precision `phi`.

<!-- real; neg_binomial_2_lupmf; (ints n | reals mu, reals phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_lupmf }!{\tt (ints n \textbar\ reals mu, reals phi): real}|hyperpage}

`real` **`neg_binomial_2_lupmf`**`(ints n | reals mu, reals phi)`<br>\newline
The negative binomial probability mass of `n` given location `mu` and
precision `phi` dropping constant additive terms.

<!-- real; neg_binomial_2_cdf; (ints n, reals mu, reals phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_cdf }!{\tt (ints n, reals mu, reals phi): real}|hyperpage}

`real` **`neg_binomial_2_cdf`**`(ints n, reals mu, reals phi)`<br>\newline
The negative binomial cumulative distribution function of `n` given
location `mu` and precision `phi`.

<!-- real; neg_binomial_2_lcdf; (ints n | reals mu, reals phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_lcdf }!{\tt (ints n \textbar\ reals mu, reals phi): real}|hyperpage}

`real` **`neg_binomial_2_lcdf`**`(ints n | reals mu, reals phi)`<br>\newline
The log of the negative binomial cumulative distribution function of `n`
given location `mu` and precision `phi`.

<!-- real; neg_binomial_2_lccdf; (ints n | reals mu, reals phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_lccdf }!{\tt (ints n \textbar\ reals mu, reals phi): real}|hyperpage}

`real` **`neg_binomial_2_lccdf`**`(ints n | reals mu, reals phi)`<br>\newline
The log of the negative binomial complementary cumulative distribution
function of `n` given location `mu` and precision `phi`.

<!-- R; neg_binomial_2_rng; (reals mu, reals phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_rng }!{\tt (reals mu, reals phi): R}|hyperpage}

`R` **`neg_binomial_2_rng`**`(reals mu, reals phi)`<br>\newline
Generate a negative binomial variate with location `mu` and precision
`phi`; may only be used in transformed data and generated quantities blocks. `mu`
must be less than $2 ^ {29}$. For a description of argument and return types, see
section [vectorized function signatures](#prob-vectorization).

## Negative binomial distribution (log alternative parameterization) {#neg-binom-2-log}

Related to the parameterization in section [negative binomial, alternative parameterization](#nbalt), the following
parameterization uses a log mean parameter $\eta = \log(\mu)$, defined
for $\eta \in \mathbb{R}$, $\phi \in \mathbb{R}^+$, so that for $n \in
\mathbb{N}$, \[ \text{NegBinomial2Log}(n \, | \, \eta, \phi) =
\text{NegBinomial2}(n | \exp(\eta), \phi). \] This alternative may be
used for sampling, as a function, and for random number generation,
but as of yet, there are no CDFs implemented for it. This is especially useful
for log-linear negative binomial regressions.

### Sampling statement

`n ~ ` **`neg_binomial_2_log`**`(eta, phi)`

Increment target log probability density with `neg_binomial_2_log_lupmf(n | eta, phi)`.
<!-- real; neg_binomial_2_log ~; -->
\index{{\tt \bfseries neg\_binomial\_2\_log }!sampling statement|hyperpage}

### Stan functions

<!-- real; neg_binomial_2_log_lpmf; (ints n | reals eta, reals phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_lpmf }!{\tt (ints n \textbar\ reals eta, reals phi): real}|hyperpage}

`real` **`neg_binomial_2_log_lpmf`**`(ints n | reals eta, reals phi)`<br>\newline
The log negative binomial probability mass of `n` given log-location `eta`
and inverse overdispersion parameter `phi`.

<!-- real; neg_binomial_2_log_lupmf; (ints n | reals eta, reals phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_lupmf }!{\tt (ints n \textbar\ reals eta, reals phi): real}|hyperpage}

`real` **`neg_binomial_2_log_lupmf`**`(ints n | reals eta, reals phi)`<br>\newline
The log negative binomial probability mass of `n` given log-location `eta`
and inverse overdispersion parameter `phi` dropping constant additive terms.

<!-- R; neg_binomial_2_log_rng; (reals eta, reals phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_rng }!{\tt (reals eta, reals phi): R}|hyperpage}

`R` **`neg_binomial_2_log_rng`**`(reals eta, reals phi)`<br>\newline
Generate a negative binomial variate with log-location `eta` and inverse
overdispersion control `phi`; may only be used in transformed data and generated
quantities blocks. `eta` must be less than $29 \log 2$. For a description of
argument and return types, see section [vectorized function signatures](#prob-vectorization).

## Negative-binomial-2-log generalized linear model (negative binomial regression) {#neg-binom-2-log-glm}

Stan also supplies a single function for a generalized linear model
with negative binomial likelihood and log link function, i.e. a
function for a negative binomial regression. This provides a
more efficient implementation of negative binomial regression than a
manually written regression in terms of a negative binomial likelihood
and matrix multiplication.

### Probability mass function

If $x\in \mathbb{R}^{n\cdot m}, \alpha \in \mathbb{R}^n, \beta\in
\mathbb{R}^m, \phi\in \mathbb{R}^+$, then for $y \in \mathbb{N}^n$, \[
\text{NegBinomial2LogGLM}(y~|~x, \alpha, \beta, \phi) = \prod_{1\leq i
\leq n}\text{NegBinomial2}(y_i~|~\exp(\alpha_i + x_i\cdot \beta),
\phi). \]

### Sampling statement

`y ~ ` **`neg_binomial_2_log_glm`**`(x, alpha, beta, phi)`

Increment target log probability density with `neg_binomial_2_log_glm_lupmf(y | x, alpha, beta, phi)`.
<!-- real; neg_binomial_2_log_glm ~; -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_glm }!sampling statement|hyperpage}

### Stan functions

<!-- real; neg_binomial_2_log_glm_lpmf; (int y | matrix x, real alpha, vector beta, real phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_glm\_lpmf }!{\tt (int y \textbar\ matrix x, real alpha, vector beta, real phi): real}|hyperpage}

`real` **`neg_binomial_2_log_glm_lpmf`**`(int y | matrix x, real alpha, vector beta, real phi)`<br>\newline
The log negative binomial probability mass of `y` given log-location
`alpha + x * beta` and inverse overdispersion parameter `phi`.

<!-- real; neg_binomial_2_log_glm_lupmf; (int y | matrix x, real alpha, vector beta, real phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_glm\_lupmf }!{\tt (int y \textbar\ matrix x, real alpha, vector beta, real phi): real}|hyperpage}

`real` **`neg_binomial_2_log_glm_lupmf`**`(int y | matrix x, real alpha, vector beta, real phi)`<br>\newline
The log negative binomial probability mass of `y` given log-location
`alpha + x * beta` and inverse overdispersion parameter `phi`
dropping constant additive terms.

<!-- real; neg_binomial_2_log_glm_lpmf; (int y | matrix x, vector alpha, vector beta, real phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_glm\_lpmf }!{\tt (int y \textbar\ matrix x, vector alpha, vector beta, real phi): real}|hyperpage}

`real` **`neg_binomial_2_log_glm_lpmf`**`(int y | matrix x, vector alpha, vector beta, real phi)`<br>\newline
The log negative binomial probability mass of `y` given log-location
`alpha + x * beta` and inverse overdispersion parameter `phi`.

<!-- real; neg_binomial_2_log_glm_lupmf; (int y | matrix x, vector alpha, vector beta, real phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_glm\_lupmf }!{\tt (int y \textbar\ matrix x, vector alpha, vector beta, real phi): real}|hyperpage}

`real` **`neg_binomial_2_log_glm_lupmf`**`(int y | matrix x, vector alpha, vector beta, real phi)`<br>\newline
The log negative binomial probability mass of `y` given log-location
`alpha + x * beta` and inverse overdispersion parameter `phi`
dropping constant additive terms.

<!-- real; neg_binomial_2_log_glm_lpmf; (int[] y | row_vector x, real alpha, vector beta, real phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_glm\_lpmf }!{\tt (int[] y \textbar\ row\_vector x, real alpha, vector beta, real phi): real}|hyperpage}

`real` **`neg_binomial_2_log_glm_lpmf`**`(int[] y | row_vector x, real alpha, vector beta, real phi)`<br>\newline
The log negative binomial probability mass of `y` given log-location
`alpha + x * beta` and inverse overdispersion parameter `phi`.

<!-- real; neg_binomial_2_log_glm_lupmf; (int[] y | row_vector x, real alpha, vector beta, real phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_glm\_lupmf }!{\tt (int[] y \textbar\ row\_vector x, real alpha, vector beta, real phi): real}|hyperpage}

`real` **`neg_binomial_2_log_glm_lupmf`**`(int[] y | row_vector x, real alpha, vector beta, real phi)`<br>\newline
The log negative binomial probability mass of `y` given log-location
`alpha + x * beta` and inverse overdispersion parameter `phi`
dropping constant additive terms.

<!-- real; neg_binomial_2_log_glm_lpmf; (int[] y | row_vector x, vector alpha, vector beta, real phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_glm\_lpmf }!{\tt (int[] y \textbar\ row\_vector x, vector alpha, vector beta, real phi): real}|hyperpage}

`real` **`neg_binomial_2_log_glm_lpmf`**`(int[] y | row_vector x, vector alpha, vector beta, real phi)`<br>\newline
The log negative binomial probability mass of `y` given log-location
`alpha + x * beta` and inverse overdispersion parameter `phi`.

<!-- real; neg_binomial_2_log_glm_lupmf; (int[] y | row_vector x, vector alpha, vector beta, real phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_glm\_lupmf }!{\tt (int[] y \textbar\ row\_vector x, vector alpha, vector beta, real phi): real}|hyperpage}

`real` **`neg_binomial_2_log_glm_lupmf`**`(int[] y | row_vector x, vector alpha, vector beta, real phi)`<br>\newline
The log negative binomial probability mass of `y` given log-location
`alpha + x * beta` and inverse overdispersion parameter `phi`
dropping constant additive terms.

<!-- real; neg_binomial_2_log_glm_lpmf; (int[] y | matrix x, real alpha, vector beta, real phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_glm\_lpmf }!{\tt (int[] y \textbar\ matrix x, real alpha, vector beta, real phi): real}|hyperpage}

`real` **`neg_binomial_2_log_glm_lpmf`**`(int[] y | matrix x, real alpha, vector beta, real phi)`<br>\newline
The log negative binomial probability mass of `y` given log-location
`alpha + x * beta` and inverse overdispersion parameter `phi`.

<!-- real; neg_binomial_2_log_glm_lupmf; (int[] y | matrix x, real alpha, vector beta, real phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_glm\_lupmf }!{\tt (int[] y \textbar\ matrix x, real alpha, vector beta, real phi): real}|hyperpage}

`real` **`neg_binomial_2_log_glm_lupmf`**`(int[] y | matrix x, real alpha, vector beta, real phi)`<br>\newline
The log negative binomial probability mass of `y` given log-location
`alpha + x * beta` and inverse overdispersion parameter `phi`
dropping constant additive terms.

<!-- real; neg_binomial_2_log_glm_lpmf; (int[] y | matrix x, vector alpha, vector beta, real phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_glm\_lpmf }!{\tt (int[] y \textbar\ matrix x, vector alpha, vector beta, real phi): real}|hyperpage}

`real` **`neg_binomial_2_log_glm_lpmf`**`(int[] y | matrix x, vector alpha, vector beta, real phi)`<br>\newline
The log negative binomial probability mass of `y` given log-location
`alpha + x * beta` and inverse overdispersion parameter `phi`.

<!-- real; neg_binomial_2_log_glm_lupmf; (int[] y | matrix x, vector alpha, vector beta, real phi); -->
\index{{\tt \bfseries neg\_binomial\_2\_log\_glm\_lupmf }!{\tt (int[] y \textbar\ matrix x, vector alpha, vector beta, real phi): real}|hyperpage}

`real` **`neg_binomial_2_log_glm_lupmf`**`(int[] y | matrix x, vector alpha, vector beta, real phi)`<br>\newline
The log negative binomial probability mass of `y` given log-location
`alpha + x * beta` and inverse overdispersion parameter `phi`
dropping constant additive terms.

## Poisson distribution {#poisson}

### Probability mass function

If $\lambda \in \mathbb{R}^+$, then for $n \in \mathbb{N}$, \[
\text{Poisson}(n|\lambda) = \frac{1}{n!} \, \lambda^n \,
\exp(-\lambda). \]

### Sampling statement

`n ~ ` **`poisson`**`(lambda)`

Increment target log probability density with `poisson_lupmf(n | lambda)`.
<!-- real; poisson ~; -->
\index{{\tt \bfseries poisson }!sampling statement|hyperpage}

### Stan functions

<!-- real; poisson_lpmf; (ints n | reals lambda); -->
\index{{\tt \bfseries poisson\_lpmf }!{\tt (ints n | reals lambda): real}|hyperpage}

`real` **`poisson_lpmf`**`(ints n | reals lambda)`<br>\newline
The log Poisson probability mass of n given rate lambda

<!-- real; poisson_lupmf; (ints n | reals lambda); -->
\index{{\tt \bfseries poisson\_lupmf }!{\tt (ints n | reals lambda): real}|hyperpage}

`real` **`poisson_lupmf`**`(ints n | reals lambda)`<br>\newline
The log Poisson probability mass of n given rate lambda dropping constant
additive terms

<!-- real; poisson_cdf; (ints n, reals lambda); -->
\index{{\tt \bfseries poisson\_cdf }!{\tt (ints n, reals lambda): real}|hyperpage}

`real` **`poisson_cdf`**`(ints n, reals lambda)`<br>\newline
The Poisson cumulative distribution function of n given rate lambda

<!-- real; poisson_lcdf; (ints n | reals lambda); -->
\index{{\tt \bfseries poisson\_lcdf }!{\tt (ints n \textbar\ reals lambda): real}|hyperpage}

`real` **`poisson_lcdf`**`(ints n | reals lambda)`<br>\newline
The log of the Poisson cumulative distribution function of n given
rate lambda

<!-- real; poisson_lccdf; (ints n | reals lambda); -->
\index{{\tt \bfseries poisson\_lccdf }!{\tt (ints n \textbar\ reals lambda): real}|hyperpage}

`real` **`poisson_lccdf`**`(ints n | reals lambda)`<br>\newline
The log of the Poisson complementary cumulative distribution function
of n given rate lambda

<!-- R; poisson_rng; (reals lambda); -->
\index{{\tt \bfseries poisson\_rng }!{\tt (reals lambda): R}|hyperpage}

`R` **`poisson_rng`**`(reals lambda)`<br>\newline
Generate a Poisson variate with rate lambda; may only be used in
transformed data and generated quantities blocks. lambda must be less than
$2^{30}$. For a description of argument and return types, see section
[vectorized function signatures](#prob-vectorization).

## Poisson distribution, log parameterization

Stan also provides a parameterization of the Poisson using the log
rate $\alpha = \log \lambda$ as a parameter.  This is useful for
log-linear Poisson regressions so that the predictor does not need to
be exponentiated and passed into the standard Poisson probability
function.

### Probability mass function

If $\alpha \in \mathbb{R}$, then for $n \in \mathbb{N}$, \[
\text{PoissonLog}(n|\alpha) = \frac{1}{n!} \, \exp \left(n\alpha -
\exp(\alpha) \right). \]

### Sampling statement

`n ~ ` **`poisson_log`**`(alpha)`

Increment target log probability density with `poisson_log_lupmf(n | alpha)`.
<!-- real; poisson_log ~; -->
\index{{\tt \bfseries poisson\_log }!sampling statement|hyperpage}

### Stan functions

<!-- real; poisson_log_lpmf; (ints n | reals alpha); -->
\index{{\tt \bfseries poisson\_log\_lpmf }!{\tt (ints n \textbar\ reals alpha): real}|hyperpage}

`real` **`poisson_log_lpmf`**`(ints n | reals alpha)`<br>\newline
The log Poisson probability mass of n given log rate alpha

<!-- real; poisson_log_lupmf; (ints n | reals alpha); -->
\index{{\tt \bfseries poisson\_log\_lupmf }!{\tt (ints n \textbar\ reals alpha): real}|hyperpage}

`real` **`poisson_log_lupmf`**`(ints n | reals alpha)`<br>\newline
The log Poisson probability mass of n given log rate alpha dropping constant
additive terms

<!-- R; poisson_log_rng; (reals alpha); -->
\index{{\tt \bfseries poisson\_log\_rng }!{\tt (reals alpha): R}|hyperpage}

`R` **`poisson_log_rng`**`(reals alpha)`<br>\newline
Generate a Poisson variate with log rate alpha; may only be used in
transformed data and generated quantities blocks. alpha must be less than
$30 \log 2$. For a description of argument and return types, see section
[vectorized function signatures](#prob-vectorization).

## Poisson-log generalized linear model (Poisson regression) {#poisson-log-glm}

Stan also supplies a single function for a generalized linear model
with Poisson likelihood and log link function, i.e. a function for a
Poisson regression. This provides a more efficient
implementation of Poisson regression than a manually written
regression in terms of a Poisson likelihood and matrix multiplication.

### Probability mass function

If $x\in \mathbb{R}^{n\cdot m}, \alpha \in \mathbb{R}^n, \beta\in
\mathbb{R}^m$, then for $y \in \mathbb{N}^n$, \[
\text{PoisonLogGLM}(y|x, \alpha, \beta) = \prod_{1\leq i \leq
n}\text{Poisson}(y_i|\exp(\alpha_i + x_i\cdot \beta)). \]

### Sampling statement

`y ~ ` **`poisson_log_glm`**`(x, alpha, beta)`

Increment target log probability density with `poisson_log_glm_lupmf(y | x, alpha, beta)`.
<!-- real; poisson_log_glm ~; -->
\index{{\tt \bfseries poisson\_log\_glm }!sampling statement|hyperpage}

### Stan functions

<!-- real; poisson_log_glm_lpmf; (int y | matrix x, real alpha, vector beta); -->
\index{{\tt \bfseries poisson\_log\_glm\_lpmf }!{\tt (int y \textbar\ matrix x, real alpha, vector beta): real}|hyperpage}

`real` **`poisson_log_glm_lpmf`**`(int y | matrix x, real alpha, vector beta)`<br>\newline
The log Poisson probability mass of `y` given the log-rate `alpha + x * beta`.

<!-- real; poisson_log_glm_lupmf; (int y | matrix x, real alpha, vector beta); -->
\index{{\tt \bfseries poisson\_log\_glm\_lupmf }!{\tt (int y \textbar\ matrix x, real alpha, vector beta): real}|hyperpage}

`real` **`poisson_log_glm_lupmf`**`(int y | matrix x, real alpha, vector beta)`<br>\newline
The log Poisson probability mass of `y` given the log-rate `alpha + x * beta`
dropping constant additive terms.

<!-- real; poisson_log_glm_lpmf; (int y | matrix x, vector alpha, vector beta); -->
\index{{\tt \bfseries poisson\_log\_glm\_lpmf }!{\tt (int y \textbar\ matrix x, vector alpha, vector beta): real}|hyperpage}

`real` **`poisson_log_glm_lpmf`**`(int y | matrix x, vector alpha, vector beta)`<br>\newline
The log Poisson probability mass of `y` given the log-rate `alpha + x * beta`.

<!-- real; poisson_log_glm_lupmf; (int y | matrix x, vector alpha, vector beta); -->
\index{{\tt \bfseries poisson\_log\_glm\_lupmf }!{\tt (int y \textbar\ matrix x, vector alpha, vector beta): real}|hyperpage}

`real` **`poisson_log_glm_lupmf`**`(int y | matrix x, vector alpha, vector beta)`<br>\newline
The log Poisson probability mass of `y` given the log-rate `alpha + x * beta`
dropping constant additive terms.

<!-- real; poisson_log_glm_lpmf; (int[] y | row_vector x, real alpha, vector beta); -->
\index{{\tt \bfseries poisson\_log\_glm\_lpmf }!{\tt (int[] y \textbar\ row\_vector x, real alpha, vector beta): real}|hyperpage}

`real` **`poisson_log_glm_lpmf`**`(int[] y | row_vector x, real alpha, vector beta)`<br>\newline
The log Poisson probability mass of `y` given the log-rate `alpha + x * beta`.

<!-- real; poisson_log_glm_lupmf; (int[] y | row_vector x, real alpha, vector beta); -->
\index{{\tt \bfseries poisson\_log\_glm\_lupmf }!{\tt (int[] y \textbar\ row\_vector x, real alpha, vector beta): real}|hyperpage}

`real` **`poisson_log_glm_lupmf`**`(int[] y | row_vector x, real alpha, vector beta)`<br>\newline
The log Poisson probability mass of `y` given the log-rate `alpha + x * beta`
dropping constant additive terms.

<!-- real; poisson_log_glm_lpmf; (int[] y | row_vector x, vector alpha, vector beta); -->
\index{{\tt \bfseries poisson\_log\_glm\_lpmf }!{\tt (int[] y \textbar\ row\_vector x, vector alpha, vector beta): real}|hyperpage}

`real` **`poisson_log_glm_lpmf`**`(int[] y | row_vector x, vector alpha, vector beta)`<br>\newline
The log Poisson probability mass of `y` given the log-rate `alpha + x * beta`.

<!-- real; poisson_log_glm_lupmf; (int[] y | row_vector x, vector alpha, vector beta); -->
\index{{\tt \bfseries poisson\_log\_glm\_lupmf }!{\tt (int[] y \textbar\ row\_vector x, vector alpha, vector beta): real}|hyperpage}

`real` **`poisson_log_glm_lupmf`**`(int[] y | row_vector x, vector alpha, vector beta)`<br>\newline
The log Poisson probability mass of `y` given the log-rate `alpha + x * beta`
dropping constant additive terms.

<!-- real; poisson_log_glm_lpmf; (int[] y | matrix x, real alpha, vector beta); -->
\index{{\tt \bfseries poisson\_log\_glm\_lpmf }!{\tt (int[] y \textbar\ matrix x, real alpha, vector beta): real}|hyperpage}

`real` **`poisson_log_glm_lpmf`**`(int[] y | matrix x, real alpha, vector beta)`<br>\newline
The log Poisson probability mass of `y` given the log-rate `alpha + x * beta`.

<!-- real; poisson_log_glm_lupmf; (int[] y | matrix x, real alpha, vector beta); -->
\index{{\tt \bfseries poisson\_log\_glm\_lupmf }!{\tt (int[] y \textbar\ matrix x, real alpha, vector beta): real}|hyperpage}

`real` **`poisson_log_glm_lupmf`**`(int[] y | matrix x, real alpha, vector beta)`<br>\newline
The log Poisson probability mass of `y` given the log-rate `alpha + x * beta`
dropping constant additive terms.

<!-- real; poisson_log_glm_lpmf; (int[] y | matrix x, vector alpha, vector beta); -->
\index{{\tt \bfseries poisson\_log\_glm\_lpmf }!{\tt (int[] y \textbar\ matrix x, vector alpha, vector beta): real}|hyperpage}

`real` **`poisson_log_glm_lpmf`**`(int[] y | matrix x, vector alpha, vector beta)`<br>\newline
The log Poisson probability mass of `y` given the log-rate `alpha + x * beta`.

<!-- real; poisson_log_glm_lupmf; (int[] y | matrix x, vector alpha, vector beta); -->
\index{{\tt \bfseries poisson\_log\_glm\_lupmf }!{\tt (int[] y \textbar\ matrix x, vector alpha, vector beta): real}|hyperpage}

`real` **`poisson_log_glm_lupmf`**`(int[] y | matrix x, vector alpha, vector beta)`<br>\newline
The log Poisson probability mass of `y` given the log-rate `alpha + x * beta`
dropping constant additive terms.


## Poisson-binomial distribution {#poisson-binomial}

### Probability mass function

If $\theta \in [0,1]^{N}$, then for $n \in \{0,\ldots,N\}$, \[
\text{Poisson-binomial}(n|\theta) = \sum_{\mathcal{C} \in \mathcal{S}_n} \prod_{i \in \mathcal{C} } \theta_i \prod_{j \in \mathcal{C}^c} (1 - \theta_j), \]
where $\mathcal{S}_n$ is the set of all subsets of size $n$ that can be built from $\{1, \dots, N\}$.

### Sampling statement

`n ~ ` **`poisson_binomial`**`(theta)`

Increment target log probability density with `poisson_lupmf(n | theta)`.
<!-- real; poisson_binomial ~; -->
\index{{\tt \bfseries poisson\_binomial }!sampling statement|hyperpage}

### Stan functions

<!-- real; poisson_binomial_lpmf; (int n | vector theta); -->
\index{{\tt \bfseries poisson\_binomial\_lpmf }!{\tt (int n | vector theta): real}|hyperpage}

`real` **`poisson_binomial_lpmf`**`(int n | vector theta)`<br>\newline
The log Poisson-binomial probability mass of `n` given success probabilities `theta`

<!-- real; poisson_binomial_lupmf; (int n | vector theta); -->
\index{{\tt \bfseries poisson\_binomial\_lupmf }!{\tt (int n | vector theta): real}|hyperpage}

`real` **`poisson_binomial_lupmf`**`(int n | vector theta)`<br>\newline
The log Poisson-binomial probability mass of `n` given success probabilities `theta` dropping constant
additive terms

<!-- real; poisson_binomial_cdf; (int n, vector theta); -->
\index{{\tt \bfseries poisson\_binomial\_cdf }!{\tt (int n, vector theta): real}|hyperpage}

`real` **`poisson_binomial_cdf`**`(int n | vector theta)`<br>\newline
The Poisson-binomial cumulative distribution function of `n` given success probabilities `theta`

<!-- real; poisson_binomial_lcdf; (int n | vector theta); -->
\index{{\tt \bfseries poisson\_binomial\_lcdf }!{\tt (int n \textbar\ vector theta): real}|hyperpage}

`real` **`poisson_binomial_lcdf`**`(int n | vector theta)`<br>\newline
The log of the Poisson-binomial cumulative distribution function of `n` given
success probabilities `theta`

<!-- real; poisson_binomial_lccdf; (int n | vector theta); -->
\index{{\tt \bfseries poisson\_binomial\_lccdf }!{\tt (int n \textbar\ vector theta): real}|hyperpage}

`real` **`poisson_binomial_lccdf`**`(int n | vector theta)`<br>\newline
The log of the Poisson-binomial complementary cumulative distribution function
of `n` given success probabilities `theta`

<!-- R; poisson_binomial_rng; (vector theta); -->
\index{{\tt \bfseries poisson\_binomial\_rng }!{\tt (vector theta): R}|hyperpage}

`R` **`poisson_binomia_rng`**`(vector theta)`<br>\newline
Generate a Poisson-binomial variate with success probabilities `theta`; may only be used in
transformed data and generated quantities blocks. For a description of argument and return types, see section
[vectorized function signatures](#prob-vectorization).
