# Unbounded Continuous Distributions

The unbounded univariate continuous probability distributions have
support on all real numbers.

```{r results='asis', echo=FALSE}
if (knitr::is_html_output()) {
cat(' * <a href="normal-distribution.html">Normal Distribution</a>\n')
cat(' * <a href="normal-id-glm.html">Normal-Id generalized Linear Model (Linear Regression)</a>\n')
cat(' * <a href="exponentially-modified-normal-distribution.html">Exponentially Modified Normal Distribution</a>\n')
cat(' * <a href="skew-normal-distribution.html">Skew Normal Distribution</a>\n')
cat(' * <a href="student-t-distribution.html">Student-T Distribution</a>\n')
cat(' * <a href="cauchy-distribution.html">Cauchy Distribution</a>\n')
cat(' * <a href="double-exponential-laplace-distribution.html">Double Exponential (Laplace) Distribution</a>\n')
cat(' * <a href="logistic-distribution.html">Logistic Distribution</a>\n')
cat(' * <a href="gumbel-distribution.html">Gumbel Distribution</a>\n')
cat(' * <a href="skew-double-exponential-distribution.html">Skew Double Exponential Distribution</a>\n')
}
```

## Normal distribution {#normal-distribution}

### Probability density function

If $\mu \in \mathbb{R}$ and $\sigma \in \mathbb{R}^+$, then for $y \in
\mathbb{R}$,
\begin{equation*}
\text{Normal}(y|\mu,\sigma) =
\frac{1}{\sqrt{2 \pi} \ \sigma} \exp\left( - \, \frac{1}{2} \left(\frac{y - \mu}{\sigma} \right)^2 \right) \!.
\end{equation*}

### Sampling statement

`y ~ ` **`normal`**`(mu, sigma)`

Increment target log probability density with `normal_lupdf(y | mu, sigma)`.
`r since("2.0")`
<!-- real; normal ~; -->
\index{{\tt \bfseries normal }!sampling statement|hyperpage}

### Stan functions

<!-- real; normal_lpdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries normal\_lpdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`normal_lpdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the normal density of y given location mu and scale sigma
`r since("2.12")`

<!-- real; normal_lupdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries normal\_lupdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`normal_lupdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the normal density of y given location mu and scale sigma dropping
constant additive terms.
`r since("2.25")`

<!-- real; normal_cdf; (reals y, reals mu, reals sigma); -->
\index{{\tt \bfseries normal\_cdf }!{\tt (reals y, reals mu, reals sigma): real}|hyperpage}

`real` **`normal_cdf`**`(reals y, reals mu, reals sigma)`<br>\newline
The cumulative normal distribution of y given location mu and scale
sigma; normal_cdf will underflow to 0 for $\frac{{y}-{\mu}}{{\sigma}}$
below -37.5 and overflow to 1 for $\frac{{y}-{\mu}}{{\sigma}}$ above
8.25; the function `Phi_approx` is more robust in the tails, but must
be scaled and translated for anything other than a standard normal.
`r since("2.0")`

<!-- real; normal_lcdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries normal\_lcdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`normal_lcdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the cumulative normal distribution of y given location mu
and scale sigma; normal_lcdf will underflow to $-\infty$ for
$\frac{{y}-{\mu}}{{\sigma}}$ below -37.5 and overflow to 0 for
$\frac{{y}-{\mu}}{{\sigma}}$ above 8.25; `log(Phi_approx(...))` is more
robust in the tails, but must be scaled and translated for anything other
than a standard normal.
`r since("2.12")`

<!-- real; normal_lccdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries normal\_lccdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`normal_lccdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the complementary cumulative normal distribution of y given
location mu and scale sigma; normal_lccdf will overflow to 0 for
$\frac{{y}-{\mu}}{{\sigma}}$ below -37.5 and underflow to $-\infty$
for $\frac{{y}-{\mu}}{{\sigma}}$ above 8.25; `log1m(Phi_approx(...))` is
more robust in the tails, but must be scaled and translated for anything
other than a standard normal.
`r since("2.15")`

<!-- R; normal_rng; (reals mu, reals sigma); -->
\index{{\tt \bfseries normal\_rng }!{\tt (reals mu, reals sigma): R}|hyperpage}

`R` **`normal_rng`**`(reals mu, reals sigma)`<br>\newline
Generate a normal variate with location mu and scale sigma; may only
be used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

### Standard normal distribution

The standard normal distribution is so-called because its parameters
are the units for their respective operations---the location (mean) is
zero and the scale (standard deviation) one.  The standard normal is
parameter-free, and the unit parameters allow considerable
simplification of the expression for the density.
\begin{equation*}
\text{StdNormal}(y) \ = \ \text{Normal}(y \mid 0, 1) \ = \
\frac{1}{\sqrt{2 \pi}} \, \exp \left( \frac{-y^2}{2} \right)\!. \end{equation*} Up
to a proportion on the log scale, where Stan computes, \begin{equation*} \log
\text{Normal}(y \mid 0, 1) \ = \ \frac{-y^2}{2} + \text{const}. \end{equation*}
With no logarithm, no subtraction, and no division by a parameter, the
standard normal log density is much more efficient to compute than the
normal log density with constant location $0$ and scale $1$.

### Sampling statement

`y ~ ` **`std_normal`**`()`

Increment target log probability density with `std_normal_lupdf(y)`.
`r since("2.19")`
<!-- real; std_normal ~; -->
\index{{\tt \bfseries std\_normal }!sampling statement|hyperpage}

### Stan functions

<!-- real; std_normal_lpdf; (reals y); -->
\index{{\tt \bfseries std\_normal\_lpdf }!{\tt (reals y): real}|hyperpage}

`real` **`std_normal_lpdf`**`(reals y)`<br>\newline
The standard normal (location zero, scale one) log probability density
of y.
`r since("2.18")`

<!-- real; std_normal_lupdf; (reals y); -->
\index{{\tt \bfseries std\_normal\_lupdf }!{\tt (reals y): real}|hyperpage}

`real` **`std_normal_lupdf`**`(reals y)`<br>\newline
The standard normal (location zero, scale one) log probability density
of y dropping constant additive terms.
`r since("2.25")`

<!-- real; std_normal_cdf; (reals y); -->
\index{{\tt \bfseries std\_normal\_cdf }!{\tt (reals y): real}|hyperpage}

`real` **`std_normal_cdf`**`(reals y)`<br>\newline
The cumulative standard normal distribution of y; std_normal_cdf will
underflow to 0 for $y$ below -37.5 and overflow to 1 for $y$ above 8.25;
the function `Phi_approx` is more robust in the tails.
`r since("2.21")`

<!-- real; std_normal_lcdf; (reals y); -->
\index{{\tt \bfseries std\_normal\_lcdf }!{\tt (reals y): real}|hyperpage}

`real` **`std_normal_lcdf`**`(reals y)`<br>\newline
The log of the cumulative standard normal distribution of y; std_normal_lcdf
will underflow to $-\infty$ for $y$ below -37.5 and overflow to 0 for $y$
above 8.25; `log(Phi_approx(...))` is more robust in the tails.
`r since("2.21")`

<!-- real; std_normal_lccdf; (reals y); -->
\index{{\tt \bfseries std\_normal\_lccdf }!{\tt (reals y): real}|hyperpage}

`real` **`std_normal_lccdf`**`(reals y)`<br>\newline
The log of the complementary cumulative standard normal distribution of y;
std_normal_lccdf will overflow to 0 for $y$ below -37.5 and underflow to
$-\infty$ for $y$ above 8.25; `log1m(Phi_approx(...))` is more robust in the
tails.
`r since("2.21")`

<!-- R; std_normal_qf; (T x); -->
\index{{\tt \bfseries std\_normal\_qf }!{\tt (T x): R}|hyperpage}

`R` **`std_normal_qf`**`(T x)`<br>\newline
Returns the value of the inverse standard normal cdf $\Phi^{-1}$ at the
specified quantile `x`. The `std_normal_qf` is equivalent to the 
`inv_Phi` function.
`r since("2.31")`

<!-- R; std_normal_log_qf; (T x); -->
\index{{\tt \bfseries std\_normal\_log\_qf }!{\tt (T x): R}|hyperpage}

`R` **`std_normal_log_qf`**`(T x)`<br>\newline
Return the value of the inverse standard normal cdf $\Phi^{-1}$ evaluated
at the log of the specified quantile `x`. This function is equivalent to
`std_normal_qf(exp(x))` but is more numerically stable.
`r since("2.31")`

<!-- real; std_normal_rng; (); -->
\index{{\tt \bfseries std\_normal\_rng }!{\tt (): real}|hyperpage}

`real` **`std_normal_rng`**`()`<br>\newline
Generate a normal variate with location zero and scale one; may only
be used in transformed data and generated quantities blocks.
`r since("2.21")`


## Normal-id generalized linear model (linear regression) {#normal-id-glm}

Stan also supplies a single function for a generalized linear model
with normal likelihood and identity link function, i.e. a function
for a linear regression. This provides a more efficient
implementation of linear regression than a manually written regression
in terms of a normal likelihood and matrix multiplication.

### Probability distribution function

If $x\in \mathbb{R}^{n\cdot m}, \alpha \in \mathbb{R}^n, \beta\in
\mathbb{R}^m, \sigma\in \mathbb{R}^+$, then for $y \in \mathbb{R}^n$,
\begin{equation*} \text{NormalIdGLM}(y|x, \alpha, \beta, \sigma) = \prod_{1\leq i
\leq n}\text{Normal}(y_i|\alpha_i + x_i\cdot \beta, \sigma). \end{equation*}

### Sampling statement

`y ~ ` **`normal_id_glm`**`(x, alpha, beta, sigma)`

Increment target log probability density with `normal_id_glm_lupdf(y | x, alpha, beta, sigma)`.
`r since("2.19")`
<!-- real; normal_id_glm ~; -->
\index{{\tt \bfseries normal\_id\_glm }!sampling statement|hyperpage}

### Stan functions

<!-- real; normal_id_glm_lpdf; (real y | matrix x, real alpha, vector beta, real sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lpdf }!{\tt (real y \textbar\ matrix x, real alpha, vector beta, real sigma): real}|hyperpage}

`real` **`normal_id_glm_lpdf`**`(real y | matrix x, real alpha, vector beta, real sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma`.
`r since("2.29")`

<!-- real; normal_id_glm_lupdf; (real y | matrix x, real alpha, vector beta, real sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lupdf }!{\tt (real y \textbar\ matrix x, real alpha, vector beta, real sigma): real}|hyperpage}

`real` **`normal_id_glm_lupdf`**`(real y | matrix x, real alpha, vector beta, real sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma` dropping constant additive terms.
`r since("2.29")`

<!-- real; normal_id_glm_lpdf; (real y | matrix x, vector alpha, vector beta, real sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lpdf }!{\tt (real y \textbar\ matrix x, vector alpha, vector beta, real sigma): real}|hyperpage}

`real` **`normal_id_glm_lpdf`**`(real y | matrix x, vector alpha, vector beta, real sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma`.
`r since("2.29")`

<!-- real; normal_id_glm_lupdf; (real y | matrix x, vector alpha, vector beta, real sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lupdf }!{\tt (real y \textbar\ matrix x, vector alpha, vector beta, real sigma): real}|hyperpage}

`real` **`normal_id_glm_lupdf`**`(real y | matrix x, vector alpha, vector beta, real sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma` dropping constant additive terms.
`r since("2.29")`

<!-- real; normal_id_glm_lpdf; (real y | matrix x, real alpha, vector beta, vector sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lpdf }!{\tt (real y \textbar\ matrix x, real alpha, vector beta, vector sigma): real}|hyperpage}

`real` **`normal_id_glm_lpdf`**`(real y | matrix x, real alpha, vector beta, vector sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma`.
`r since("2.23")`

<!-- real; normal_id_glm_lupdf; (real y | matrix x, real alpha, vector beta, vector sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lupdf }!{\tt (real y \textbar\ matrix x, real alpha, vector beta, vector sigma): real}|hyperpage}

`real` **`normal_id_glm_lupdf`**`(real y | matrix x, real alpha, vector beta, vector sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma` dropping constant additive terms.
`r since("2.25")`

<!-- real; normal_id_glm_lpdf; (real y | matrix x, vector alpha, vector beta, vector sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lpdf }!{\tt (real y \textbar\ matrix x, vector alpha, vector beta, vector sigma): real}|hyperpage}

`real` **`normal_id_glm_lpdf`**`(real y | matrix x, vector alpha, vector beta, vector sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma`.
`r since("2.23")`

<!-- real; normal_id_glm_lupdf; (real y | matrix x, vector alpha, vector beta, vector sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lupdf }!{\tt (real y \textbar\ matrix x, vector alpha, vector beta, vector sigma): real}|hyperpage}

`real` **`normal_id_glm_lupdf`**`(real y | matrix x, vector alpha, vector beta, vector sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma` dropping constant additive terms.
`r since("2.25")`

<!-- real; normal_id_glm_lpdf; (vector y | row_vector x, real alpha, vector beta, real sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lpdf }!{\tt (vector y \textbar\ row\_vector x, real alpha, vector beta, real sigma): real}|hyperpage}

`real` **`normal_id_glm_lpdf`**`(vector y | row_vector x, real alpha, vector beta, real sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma`.
`r since("2.29")`

<!-- real; normal_id_glm_lupdf; (vector y | row_vector x, real alpha, vector beta, real sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lupdf }!{\tt (vector y \textbar\ row\_vector x, real alpha, vector beta, real sigma): real}|hyperpage}

`real` **`normal_id_glm_lupdf`**`(vector y | row_vector x, real alpha, vector beta, real sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma` dropping constant additive terms.
`r since("2.29")`

<!-- real; normal_id_glm_lpdf; (vector y | row_vector x, vector alpha, vector beta, real sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lpdf }!{\tt (vector y \textbar\ row\_vector x, vector alpha, vector beta, real sigma): real}|hyperpage}

`real` **`normal_id_glm_lpdf`**`(vector y | row_vector x, vector alpha, vector beta, real sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma`.
`r since("2.29")`

<!-- real; normal_id_glm_lupdf; (vector y | row_vector x, vector alpha, vector beta, real sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lupdf }!{\tt (vector y \textbar\ row\_vector x, vector alpha, vector beta, real sigma): real}|hyperpage}

`real` **`normal_id_glm_lupdf`**`(vector y | row_vector x, vector alpha, vector beta, real sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma` dropping constant additive terms.
`r since("2.29")`

<!-- real; normal_id_glm_lpdf; (vector y | matrix x, real alpha, vector beta, real sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lpdf }!{\tt (vector y \textbar\ matrix x, real alpha, vector beta, real sigma): real}|hyperpage}

`real` **`normal_id_glm_lpdf`**`(vector y | matrix x, real alpha, vector beta, real sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma`.
`r since("2.23")`

<!-- real; normal_id_glm_lupdf; (vector y | matrix x, real alpha, vector beta, real sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lupdf }!{\tt (vector y \textbar\ matrix x, real alpha, vector beta, real sigma): real}|hyperpage}

`real` **`normal_id_glm_lupdf`**`(vector y | matrix x, real alpha, vector beta, real sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma` dropping constant additive terms.
`r since("2.23")`

<!-- real; normal_id_glm_lpdf; (vector y | matrix x, vector alpha, vector beta, real sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lpdf }!{\tt (vector y \textbar\ matrix x, vector alpha, vector beta, real sigma): real}|hyperpage}

`real` **`normal_id_glm_lpdf`**`(vector y | matrix x, vector alpha, vector beta, real sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma`.
`r since("2.23")`

<!-- real; normal_id_glm_lupdf; (vector y | matrix x, vector alpha, vector beta, real sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lupdf }!{\tt (vector y \textbar\ matrix x, vector alpha, vector beta, real sigma): real}|hyperpage}

`real` **`normal_id_glm_lupdf`**`(vector y | matrix x, vector alpha, vector beta, real sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma` dropping constant additive terms.
`r since("2.23")`

<!-- real; normal_id_glm_lpdf; (vector y | matrix x, real alpha, vector beta, vector sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lpdf }!{\tt (vector y \textbar\ matrix x, real alpha, vector beta, vector sigma): real}|hyperpage}

`real` **`normal_id_glm_lpdf`**`(vector y | matrix x, real alpha, vector beta, vector sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma`.
`r since("2.30")`

<!-- real; normal_id_glm_lupdf; (vector y | matrix x, real alpha, vector beta, vector sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lupdf }!{\tt (vector y \textbar\ matrix x, real alpha, vector beta, vector sigma): real}|hyperpage}

`real` **`normal_id_glm_lupdf`**`(vector y | matrix x, real alpha, vector beta, vector sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma` dropping constant additive terms.
`r since("2.30")`

<!-- real; normal_id_glm_lpdf; (vector y | matrix x, vector alpha, vector beta, vector sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lpdf }!{\tt (vector y \textbar\ matrix x, vector alpha, vector beta, vector sigma): real}|hyperpage}

`real` **`normal_id_glm_lpdf`**`(vector y | matrix x, vector alpha, vector beta, vector sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma`.
`r since("2.30")`

<!-- real; normal_id_glm_lupdf; (vector y | matrix x, vector alpha, vector beta, vector sigma); -->
\index{{\tt \bfseries normal\_id\_glm\_lupdf }!{\tt (vector y \textbar\ matrix x, vector alpha, vector beta, vector sigma): real}|hyperpage}

`real` **`normal_id_glm_lupdf`**`(vector y | matrix x, vector alpha, vector beta, vector sigma)`<br>\newline
The log normal probability density of `y` given location `alpha + x * beta`
and scale `sigma` dropping constant additive terms.
`r since("2.30")`

## Exponentially modified normal distribution

### Probability density function

If $\mu \in \mathbb{R}$, $\sigma \in \mathbb{R}^+$, and $\lambda \in
\mathbb{R}^+$, then for $y \in \mathbb{R}$, \begin{equation*}
\text{ExpModNormal}(y|\mu,\sigma,\lambda) = \frac{\lambda}{2} \ \exp
\left(\frac{\lambda}{2} \left(2\mu + \lambda \sigma^2 -
2y\right)\right) \text{erfc}\left(\frac{\mu + \lambda\sigma^2 -
y}{\sqrt{2}\sigma}\right) . \end{equation*}

### Sampling statement

`y ~ ` **`exp_mod_normal`**`(mu, sigma, lambda)`

Increment target log probability density with `exp_mod_normal_lupdf(y | mu, sigma, lambda)`.
`r since("2.0")`
<!-- real; exp_mod_normal ~; -->
\index{{\tt \bfseries exp\_mod\_normal }!sampling statement|hyperpage}

### Stan functions

<!-- real; exp_mod_normal_lpdf; (reals y | reals mu, reals sigma, reals lambda); -->
\index{{\tt \bfseries exp\_mod\_normal\_lpdf }!{\tt (reals y | reals mu, reals sigma, reals lambda): real}|hyperpage}

`real` **`exp_mod_normal_lpdf`**`(reals y | reals mu, reals sigma, reals lambda)`<br>\newline
The log of the exponentially modified normal density of y given
location mu, scale sigma, and shape lambda
`r since("2.18")`

<!-- real; exp_mod_normal_lupdf; (reals y | reals mu, reals sigma, reals lambda); -->
\index{{\tt \bfseries exp\_mod\_normal\_lupdf }!{\tt (reals y | reals mu, reals sigma, reals lambda): real}|hyperpage}

`real` **`exp_mod_normal_lupdf`**`(reals y | reals mu, reals sigma, reals lambda)`<br>\newline
The log of the exponentially modified normal density of y given
location mu, scale sigma, and shape lambda dropping constant additive terms
`r since("2.25")`

<!-- real; exp_mod_normal_cdf; (reals y, reals mu, reals sigma, reals lambda); -->
\index{{\tt \bfseries exp\_mod\_normal\_cdf }!{\tt (reals y, reals mu, reals sigma, reals lambda): real}|hyperpage}

`real` **`exp_mod_normal_cdf`**`(reals y, reals mu, reals sigma, reals lambda)`<br>\newline
The exponentially modified normal cumulative distribution function of
y given location mu, scale sigma, and shape lambda
`r since("2.0")`

<!-- real; exp_mod_normal_lcdf; (reals y | reals mu, reals sigma, reals lambda); -->
\index{{\tt \bfseries exp\_mod\_normal\_lcdf }!{\tt (reals y | reals mu, reals sigma, reals lambda): real}|hyperpage}

`real` **`exp_mod_normal_lcdf`**`(reals y | reals mu, reals sigma, reals lambda)`<br>\newline
The log of the exponentially modified normal cumulative distribution
function of y given location mu, scale sigma, and shape lambda
`r since("2.18")`

<!-- real; exp_mod_normal_lccdf; (reals y | reals mu, reals sigma, reals lambda); -->
\index{{\tt \bfseries exp\_mod\_normal\_lccdf }!{\tt (reals y \textbar\ reals mu, reals sigma, reals lambda): real}|hyperpage}

`real` **`exp_mod_normal_lccdf`**`(reals y | reals mu, reals sigma, reals lambda)`<br>\newline
The log of the exponentially modified normal complementary cumulative
distribution function of y given location mu, scale sigma, and shape
lambda
`r since("2.18")`

<!-- R; exp_mod_normal_rng; (reals mu, reals sigma, reals lambda); -->
\index{{\tt \bfseries exp\_mod\_normal\_rng }!{\tt (reals mu, reals sigma, reals lambda): R}|hyperpage}

`R` **`exp_mod_normal_rng`**`(reals mu, reals sigma, reals lambda)`<br>\newline
Generate a exponentially modified normal variate with location mu,
scale sigma, and shape lambda; may only be used in transformed data and generated
quantities blocks. For a description of argument and return types, see
section [vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Skew normal distribution

### Probability density function

If $\xi \in \mathbb{R}$, $\omega \in \mathbb{R}^+$, and $\alpha \in
\mathbb{R}$, then for $y \in \mathbb{R}$, \begin{equation*} \text{SkewNormal}(y \mid
\xi, \omega, \alpha) = \frac{1}{\omega\sqrt{2\pi}} \ \exp\left( - \,
\frac{1}{2}            \left(  \frac{y - \xi}{\omega} \right)^2
\right) \ \left(1 + \text{erf}\left( \alpha\left(\frac{y -
\xi}{\omega\sqrt{2}}\right)\right)\right) . \end{equation*}

### Sampling statement

`y ~ ` **`skew_normal`**`(xi, omega, alpha)`

Increment target log probability density with `skew_normal_lupdf(y | xi, omega, alpha)`.
`r since("2.0")`
<!-- real; skew_normal ~; -->
\index{{\tt \bfseries skew\_normal }!sampling statement|hyperpage}

### Stan functions

<!-- real; skew_normal_lpdf; (reals y | reals xi, reals omega, reals alpha); -->
\index{{\tt \bfseries skew\_normal\_lpdf }!{\tt (reals y \textbar\ reals xi, reals omega, reals alpha): real}|hyperpage}

`real` **`skew_normal_lpdf`**`(reals y | reals xi, reals omega, reals alpha)`<br>\newline
The log of the skew normal density of y given location xi, scale
omega, and shape alpha
`r since("2.16")`

<!-- real; skew_normal_lupdf; (reals y | reals xi, reals omega, reals alpha); -->
\index{{\tt \bfseries skew\_normal\_lupdf }!{\tt (reals y \textbar\ reals xi, reals omega, reals alpha): real}|hyperpage}

`real` **`skew_normal_lupdf`**`(reals y | reals xi, reals omega, reals alpha)`<br>\newline
The log of the skew normal density of y given location xi, scale
omega, and shape alpha dropping constant additive terms
`r since("2.25")`

<!-- real; skew_normal_cdf; (reals y, reals xi, reals omega, reals alpha); -->
\index{{\tt \bfseries skew\_normal\_cdf }!{\tt (reals y, reals xi, reals omega, reals alpha): real}|hyperpage}

`real` **`skew_normal_cdf`**`(reals y, reals xi, reals omega, reals alpha)`<br>\newline
The skew normal distribution function of y given location xi, scale
omega, and shape alpha
`r since("2.16")`

<!-- real; skew_normal_lcdf; (reals y | reals xi, reals omega, reals alpha); -->
\index{{\tt \bfseries skew\_normal\_lcdf }!{\tt (reals y \textbar\ reals xi, reals omega, reals alpha): real}|hyperpage}

`real` **`skew_normal_lcdf`**`(reals y | reals xi, reals omega, reals alpha)`<br>\newline
The log of the skew normal cumulative distribution function of y given
location xi, scale omega, and shape alpha
`r since("2.18")`

<!-- real; skew_normal_lccdf; (reals y | reals xi, reals omega, reals alpha); -->
\index{{\tt \bfseries skew\_normal\_lccdf }!{\tt (reals y \textbar\ reals xi, reals omega, reals alpha): real}|hyperpage}

`real` **`skew_normal_lccdf`**`(reals y | reals xi, reals omega, reals alpha)`<br>\newline
The log of the skew normal complementary cumulative distribution
function of y given location xi, scale omega, and shape alpha
`r since("2.18")`

<!-- R; skew_normal_rng; (reals xi, reals omega, real alpha); -->
\index{{\tt \bfseries skew\_normal\_rng }!{\tt (reals xi, reals omega, real alpha): R}|hyperpage}

`R` **`skew_normal_rng`**`(reals xi, reals omega, real alpha)`<br>\newline
Generate a skew normal variate with location xi, scale omega, and
shape alpha; may only be used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Student-t distribution

### Probability density function

If $\nu \in \mathbb{R}^+$, $\mu \in \mathbb{R}$, and $\sigma \in
\mathbb{R}^+$, then for $y \in \mathbb{R}$, \begin{equation*}
\text{StudentT}(y|\nu,\mu,\sigma) = \frac{\Gamma\left((\nu +
1)/2\right)}      {\Gamma(\nu/2)} \ \frac{1}{\sqrt{\nu \pi} \ \sigma}
\ \left( 1 + \frac{1}{\nu} \left(\frac{y - \mu}{\sigma}\right)^2
\right)^{-(\nu + 1)/2} \! . \end{equation*}

### Sampling statement

`y ~ ` **`student_t`**`(nu, mu, sigma)`

Increment target log probability density with `student_t_lupdf(y | nu, mu, sigma)`.
`r since("2.0")`
<!-- real; student_t ~; -->
\index{{\tt \bfseries student\_t }!sampling statement|hyperpage}

### Stan functions

<!-- real; student_t_lpdf; (reals y | reals nu, reals mu, reals sigma); -->
\index{{\tt \bfseries student\_t\_lpdf }!{\tt (reals y \textbar\ reals nu, reals mu, reals sigma): real}|hyperpage}

`real` **`student_t_lpdf`**`(reals y | reals nu, reals mu, reals sigma)`<br>\newline
The log of the Student-$t$ density of y given degrees of freedom nu,
location mu, and scale sigma
`r since("2.12")`

<!-- real; student_t_lupdf; (reals y | reals nu, reals mu, reals sigma); -->
\index{{\tt \bfseries student\_t\_lupdf }!{\tt (reals y \textbar\ reals nu, reals mu, reals sigma): real}|hyperpage}

`real` **`student_t_lupdf`**`(reals y | reals nu, reals mu, reals sigma)`<br>\newline
The log of the Student-$t$ density of y given degrees of freedom nu,
location mu, and scale sigma dropping constant additive terms
`r since("2.25")`

<!-- real; student_t_cdf; (reals y, reals nu, reals mu, reals sigma); -->
\index{{\tt \bfseries student\_t\_cdf }!{\tt (reals y, reals nu, reals mu, reals sigma): real}|hyperpage}

`real` **`student_t_cdf`**`(reals y, reals nu, reals mu, reals sigma)`<br>\newline
The Student-$t$ cumulative distribution function of y given degrees of
freedom nu, location mu, and scale sigma
`r since("2.0")`

<!-- real; student_t_lcdf; (reals y | reals nu, reals mu, reals sigma); -->
\index{{\tt \bfseries student\_t\_lcdf }!{\tt (reals y \textbar\ reals nu, reals mu, reals sigma): real}|hyperpage}

`real` **`student_t_lcdf`**`(reals y | reals nu, reals mu, reals sigma)`<br>\newline
The log of the Student-$t$ cumulative distribution function of y given
degrees of freedom nu, location mu, and scale sigma
`r since("2.12")`

<!-- real; student_t_lccdf; (reals y | reals nu, reals mu, reals sigma); -->
\index{{\tt \bfseries student\_t\_lccdf }!{\tt (reals y \textbar\ reals nu, reals mu, reals sigma): real}|hyperpage}

`real` **`student_t_lccdf`**`(reals y | reals nu, reals mu, reals sigma)`<br>\newline
The log of the Student-$t$ complementary cumulative distribution
function of y given degrees of freedom nu, location mu, and scale
sigma
`r since("2.12")`

<!-- R; student_t_rng; (reals nu, reals mu, reals sigma); -->
\index{{\tt \bfseries student\_t\_rng }!{\tt (reals nu, reals mu, reals sigma): R}|hyperpage}

`R` **`student_t_rng`**`(reals nu, reals mu, reals sigma)`<br>\newline
Generate a Student-$t$ variate with degrees of freedom nu, location
mu, and scale sigma; may only be used in transformed data and generated
quantities blocks. For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Cauchy distribution

### Probability density function

If $\mu \in \mathbb{R}$ and $\sigma \in \mathbb{R}^+$, then for $y \in \mathbb{R}$,
\begin{equation*}
\text{Cauchy}(y|\mu,\sigma) = \frac{1}{\pi \sigma} \ \frac{1}{1 + \left((y - \mu)/\sigma\right)^2} .
\end{equation*}

### Sampling statement

`y ~ ` **`cauchy`**`(mu, sigma)`

Increment target log probability density with `cauchy_lupdf(y | mu, sigma)`.
`r since("2.0")`
<!-- real; cauchy ~; -->
\index{{\tt \bfseries cauchy }!sampling statement|hyperpage}

### Stan functions

<!-- real; cauchy_lpdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries cauchy\_lpdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`cauchy_lpdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the Cauchy density of y given location mu and scale sigma
`r since("2.12")`

<!-- real; cauchy_lupdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries cauchy\_lupdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`cauchy_lupdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the Cauchy density of y given location mu and scale sigma
dropping constant additive terms
`r since("2.25")`

<!-- real; cauchy_cdf; (reals y, reals mu, reals sigma); -->
\index{{\tt \bfseries cauchy\_cdf }!{\tt (reals y, reals mu, reals sigma): real}|hyperpage}

`real` **`cauchy_cdf`**`(reals y, reals mu, reals sigma)`<br>\newline
The Cauchy cumulative distribution function of y given location mu and
scale sigma
`r since("2.0")`

<!-- real; cauchy_lcdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries cauchy\_lcdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`cauchy_lcdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the Cauchy cumulative distribution function of y given
location mu and scale sigma
`r since("2.12")`

<!-- real; cauchy_lccdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries cauchy\_lccdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`cauchy_lccdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the Cauchy complementary cumulative distribution function
of y given location mu and scale sigma
`r since("2.12")`

<!-- R; cauchy_rng; (reals mu, reals sigma); -->
\index{{\tt \bfseries cauchy\_rng }!{\tt (reals mu, reals sigma): R}|hyperpage}

`R` **`cauchy_rng`**`(reals mu, reals sigma)`<br>\newline
Generate a Cauchy variate with location mu and scale sigma; may only
be used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Double exponential (Laplace) distribution

### Probability density function

If $\mu \in \mathbb{R}$ and $\sigma \in \mathbb{R}^+$, then for $y \in
\mathbb{R}$, \begin{equation*} \text{DoubleExponential}(y|\mu,\sigma) =
\frac{1}{2\sigma}   \exp \left( - \, \frac{|y - \mu|}{\sigma} \right)
. \end{equation*} Note that the double exponential distribution is parameterized in
terms of the scale, in contrast to the exponential distribution (see
section [exponential distribution](#exponential-distribution)), which is
parameterized in terms of inverse scale.

The double-exponential distribution can be defined as a compound
exponential-normal distribution [@Ding:18]. Using the inverse scale
parameterization for the exponential distribution, and the standard deviation
parameterization for the normal distribution, one can write \begin{equation*} \alpha \sim
\mathsf{Exponential}\left( \frac{1}{2 \sigma^2} \right) \end{equation*} and \begin{equation*} \beta \mid
\alpha \sim \mathsf{Normal}(\mu, \sqrt{\alpha}), \end{equation*} then \begin{equation*} \beta \sim
\mathsf{DoubleExponential}(\mu, \sigma ). \end{equation*} This may be used to code
a non-centered parameterization by taking \begin{equation*} \beta^{\text{raw}} \sim
\mathsf{Normal}(0, 1) \end{equation*} and defining \begin{equation*} \beta = \mu + \sqrt{\alpha} \,
\beta^{\text{raw}}. \end{equation*}


### Sampling statement

`y ~ ` **`double_exponential`**`(mu, sigma)`

Increment target log probability density with `double_exponential_lupdf(y | mu, sigma)`.
`r since("2.0")`
<!-- real; double_exponential ~; -->
\index{{\tt \bfseries double\_exponential }!sampling statement|hyperpage}

### Stan functions

<!-- real; double_exponential_lpdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries double\_exponential\_lpdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`double_exponential_lpdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the double exponential density of y given location mu and
scale sigma
`r since("2.12")`

<!-- real; double_exponential_lupdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries double\_exponential\_lupdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`double_exponential_lupdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the double exponential density of y given location mu and
scale sigma dropping constant additive terms
`r since("2.25")`

<!-- real; double_exponential_cdf; (reals y, reals mu, reals sigma); -->
\index{{\tt \bfseries double\_exponential\_cdf }!{\tt (reals y, reals mu, reals sigma): real}|hyperpage}

`real` **`double_exponential_cdf`**`(reals y, reals mu, reals sigma)`<br>\newline
The double exponential cumulative distribution function of y given
location mu and scale sigma
`r since("2.0")`

<!-- real; double_exponential_lcdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries double\_exponential\_lcdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`double_exponential_lcdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the double exponential cumulative distribution function of
y given location mu and scale sigma
`r since("2.12")`

<!-- real; double_exponential_lccdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries double\_exponential\_lccdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`double_exponential_lccdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the double exponential complementary cumulative
distribution function of y given location mu and scale sigma
`r since("2.12")`

<!-- R; double_exponential_rng; (reals mu, reals sigma); -->
\index{{\tt \bfseries double\_exponential\_rng }!{\tt (reals mu, reals sigma): R}|hyperpage}

`R` **`double_exponential_rng`**`(reals mu, reals sigma)`<br>\newline
Generate a double exponential variate with location mu and scale
sigma; may only be used in transformed data and generated quantities blocks. For a
description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Logistic distribution

### Probability density function

If $\mu \in \mathbb{R}$ and $\sigma \in \mathbb{R}^+$, then for $y \in \mathbb{R}$,
\begin{equation*}
\text{Logistic}(y|\mu,\sigma) = \frac{1}{\sigma} \ \exp\!\left( - \, \frac{y - \mu}{\sigma} \right)
\ \left(1 + \exp \!\left( - \, \frac{y - \mu}{\sigma} \right) \right)^{\!-2} \! .
\end{equation*}

### Sampling statement

`y ~ ` **`logistic`**`(mu, sigma)`

Increment target log probability density with `logistic_lupdf(y | mu, sigma)`.
`r since("2.0")`
<!-- real; logistic ~; -->
\index{{\tt \bfseries logistic }!sampling statement|hyperpage}

### Stan functions

<!-- real; logistic_lpdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries logistic\_lpdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`logistic_lpdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the logistic density of y given location mu and scale sigma
`r since("2.12")`

<!-- real; logistic_lupdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries logistic\_lupdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`logistic_lupdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the logistic density of y given location mu and scale sigma
dropping constant additive terms
`r since("2.25")`

<!-- real; logistic_cdf; (reals y, reals mu, reals sigma); -->
\index{{\tt \bfseries logistic\_cdf }!{\tt (reals y, reals mu, reals sigma): real}|hyperpage}

`real` **`logistic_cdf`**`(reals y, reals mu, reals sigma)`<br>\newline
The logistic cumulative distribution function of y given location mu
and scale sigma
`r since("2.0")`

<!-- real; logistic_lcdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries logistic\_lcdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`logistic_lcdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the logistic cumulative distribution function of y given
location mu and scale sigma
`r since("2.12")`

<!-- real; logistic_lccdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries logistic\_lccdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}

`real` **`logistic_lccdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the logistic complementary cumulative distribution function
of y given location mu and scale sigma
`r since("2.12")`

<!-- R; logistic_rng; (reals mu, reals sigma); -->
\index{{\tt \bfseries logistic\_rng}!{\tt (reals mu, reals sigma): R}|hyperpage}

`R` **`logistic_rng`**`(reals mu, reals sigma)`<br>\newline
Generate a logistic variate with location mu and scale sigma; may only
be used in transformed data and generated quantities blocks.
For a description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Gumbel distribution

### Probability density function

If $\mu \in \mathbb{R}$ and $\beta \in \mathbb{R}^+$, then for $y \in \mathbb{R}$,
\begin{equation*}
\text{Gumbel}(y|\mu,\beta) = \frac{1}{\beta} \ \exp\left(-\frac{y-\mu}{\beta}-\exp\left(-\frac{y-\mu}{\beta}\right)\right) .
\end{equation*}

### Sampling statement

`y ~ ` **`gumbel`**`(mu, beta)`

Increment target log probability density with `gumbel_lupdf(y | mu, beta)`.
`r since("2.0")`
<!-- real; gumbel ~; -->
\index{{\tt \bfseries gumbel }!sampling statement|hyperpage}

### Stan functions

<!-- real; gumbel_lpdf; (reals y | reals mu, reals beta); -->
\index{{\tt \bfseries gumbel\_lpdf }!{\tt (reals y \textbar\ reals mu, reals beta): real}|hyperpage}

`real` **`gumbel_lpdf`**`(reals y | reals mu, reals beta)`<br>\newline
The log of the gumbel density of y given location mu and scale beta
`r since("2.12")`

<!-- real; gumbel_lupdf; (reals y | reals mu, reals beta); -->
\index{{\tt \bfseries gumbel\_lupdf }!{\tt (reals y \textbar\ reals mu, reals beta): real}|hyperpage}

`real` **`gumbel_lupdf`**`(reals y | reals mu, reals beta)`<br>\newline
The log of the gumbel density of y given location mu and scale beta
dropping constant additive terms
`r since("2.25")`

<!-- real; gumbel_cdf; (reals y, reals mu, reals beta); -->
\index{{\tt \bfseries gumbel\_cdf }!{\tt (reals y, reals mu, reals beta): real}|hyperpage}

`real` **`gumbel_cdf`**`(reals y, reals mu, reals beta)`<br>\newline
The gumbel cumulative distribution function of y given location mu and
scale beta
`r since("2.0")`

<!-- real; gumbel_lcdf; (reals y | reals mu, reals beta); -->
\index{{\tt \bfseries gumbel\_lcdf }!{\tt (reals y \textbar\ reals mu, reals beta): real}|hyperpage}

`real` **`gumbel_lcdf`**`(reals y | reals mu, reals beta)`<br>\newline
The log of the gumbel cumulative distribution function of y given
location mu and scale beta
`r since("2.12")`

<!-- real; gumbel_lccdf; (reals y | reals mu, reals beta); -->
\index{{\tt \bfseries gumbel\_lccdf }!{\tt (reals y \textbar\ reals mu, reals beta): real}|hyperpage}

`real` **`gumbel_lccdf`**`(reals y | reals mu, reals beta)`<br>\newline
The log of the gumbel complementary cumulative distribution function
of y given location mu and scale beta
`r since("2.12")`

<!-- R; gumbel_rng; (reals mu, reals beta); -->
\index{{\tt \bfseries gumbel\_rng }!{\tt (reals mu, reals beta): R}|hyperpage}

`R` **`gumbel_rng`**`(reals mu, reals beta)`<br>\newline
Generate a gumbel variate with location mu and scale beta; may only be
used in transformed data and generated quantities blocks. For a description
of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.18")`

## Skew double exponential distribution

### Probability density function

If $\mu \in \mathbb{R}$, $\sigma \in \mathbb{R}^+$ and $\tau \in [0, 1]$,
then for $y \in \mathbb{R}$,
$$\begin{aligned}
& \text{SkewDoubleExponential}  (y|\mu,\sigma, \tau) = \\
& \qquad \qquad \frac{2 \tau (1 - \tau) }{\sigma} \exp \left[ - \frac{2}{\sigma} \left[ \left(1 - \tau \right) I(y < \mu)  (\mu - y) + \tau I(y > \mu)(y-\mu)  \right]    \right]
\end{aligned}$$


### Sampling statement

`y ~ ` **`skew_double_exponential`**`(mu, sigma, tau)`

Increment target log probability density with `skew_double_exponential(y | mu, sigma, tau)`
`r since("2.28")`
<!-- real; skew_double_exponential ~; -->
\index{{\tt \bfseries skew\_double\_exponential }!sampling statement|hyperpage}

### Stan functions

<!-- real; skew_double_exponential_lpdf; (reals y | reals mu, reals sigma, reals tau); -->
\index{{\tt \bfseries skew\_double\_exponential\_lpdf }!{\tt (reals y \textbar\ reals mu, reals sigma, reals tau): real}|hyperpage}

`real` **`skew_double_exponential_lpdf`**`(reals y | reals mu, reals sigma, reals tau)`<br>\newline
The log of the skew double exponential density of y given location mu, scale sigma and skewness tau
`r since("2.28")`

<!-- real; skew_double_exponential_lupdf; (reals y | reals mu, reals sigma, reals tau); -->
\index{{\tt \bfseries skew\_double\_exponential\_lupdf }!{\tt (reals y \textbar\ reals mu, reals sigma, reals tau): real}|hyperpage}

`real` **`skew_double_exponential_lupdf`**`(reals y | reals mu, reals sigma, reals tau)`<br>\newline
The log of the skew double exponential density of y given location mu, scale sigma and skewness tau dropping constant additive terms
`r since("2.28")`

<!-- real; skew_double_exponential_cdf; (reals y, reals mu, reals sigma, reals tau); -->
\index{{\tt \bfseries skew\_double\_exponential\_cdf }!{\tt (reals y, reals mu, reals sigma, reals tau): real}|hyperpage}

`real` **`skew_double_exponential_cdf`**`(reals y, reals mu, reals sigma, reals tau)`<br>\newline
The skew double exponential cumulative distribution function of y given
location mu, scale sigma and skewness tau
`r since("2.28")`

<!-- real; skew_double_exponential_lcdf; (reals y | reals mu, reals sigma, reals tau); -->
\index{{\tt \bfseries skew\_double\_exponential\_lcdf }!{\tt (reals y \textbar\ reals mu, reals sigma, reals tau): real}|hyperpage}

`real` **`skew_double_exponential_lcdf`**`(reals y | reals mu, reals sigma, reals tau)`<br>\newline
The log of the skew double exponential cumulative distribution function of
y given location mu, scale sigma and skewness tau
`r since("2.28")`

<!-- real; skew_double_exponential_lccdf; (reals y | reals mu, reals sigma, reals tau); -->
\index{{\tt \bfseries skew\_double\_exponential\_lccdf }!{\tt (reals y \textbar\ reals mu, reals sigma, reals tau): real}|hyperpage}

`real` **`skew_double_exponential_lccdf`**`(reals y | reals mu, reals sigma, reals tau)`<br>\newline
The log of the skew double exponential complementary cumulative
distribution function of y given location mu, scale sigma and skewness tau
`r since("2.28")`

<!-- R; skew_double_exponential_rng; (reals mu, reals sigma); -->
\index{{\tt \bfseries skew\_double\_exponential\_rng }!{\tt (reals mu, reals sigma, reals tau): R}|hyperpage}

`R` **`skew_double_exponential_rng`**`(reals mu, reals sigma, reals tau)`<br>\newline
Generate a skew double exponential variate with location mu, scale
sigma and skewness tau; may only be used in transformed data and generated quantities blocks. For a
description of argument and return types, see section
[vectorized PRNG functions](#prng-vectorization).
`r since("2.28")`
