# Error messages and return codes {#err-codes}

CmdStan executables and utility programs use streams standard output (stdout) and
standard error (stderr) to report information and error messages, respectively.

All program executables provide a return code between 0 and 255:


- 0 - Program ran to termination as expected.

- value in range [1 : 125] - Method invoked could not run due to problems with model or data.

- value > 128 - Fatal error during execution, process terminated by signal.  The signal number is retcode - 128.


Common sources of program error are:

- Missing or ill-formed input data.  All variables declared in the data block must be supplied in the input data file.

- Model parameters cannot be initialized due to model misspecification.

- Indexing errors.  The Stan language provides indexing and slicing operations.  Indexing errors are easy to make and difficult to debug.  The compiler and runtime detect index out of bounds errors; they cannot detect the semantic errors such as indexing into the wrong variables or incorrect index updates.

