---
title: "CmdStan User's Guide"
subtitle: "`r paste('Version', Sys.getenv('STAN_DOCS_VERSION'))`"
author: "Stan Development Team"
description: "CmdStan user's guide."
site: bookdown::bookdown_site
cover-image: img/logo-tm.pdf
documentclass: book
classoption: oneside, openany
bibliography: [../bibtex/all.bib]
biblio-style: apalike
link-citations: true
fontsize: 10pt
monofont: "Lucida Console"
subparagraph: true
always_allow_html: true
---

# <i style='font-size: 110%; color:#990017;'>Introduction</i> {-}

This document is a user's guide for CmdStan, the command-line interface
to the Stan statistical modeling language.
CmdStan provides the programs and tools to compile Stan programs into
C++ executables that can be run directly from the command line, together
with a few utilities to check and summarize the resulting outputs.

In CmdStan, statistical models written in the Stan probabilistic programming language
are translated into a C++ program which is then compiled together with the CmdStan routines
that provide the logic needed to manage all user inputs and program outputs
and the Stan inference algorithms and math library.
The resulting command line executable program can be used to

- do inference on data, producing an exact or approximate estimate of the posterior;

- generate new quantities of interest from an existing estimate;

- generate data from the model according to a given set of parameters.

The packages CmdStanR and CmdStanPy provide interfaces to CmdStan from R and Python,
respectively, similarly, JuliaStan also interfaces with CmdStan.

#### Stan home page {-}

For links to up-to-date code, examples, manuals, bug reports, feature
requests, and everything else Stan related, see the Stan home page:

http://mc-stan.org/

#### Licensing {-}

CmdStan, Stan, and the Stan Math Library are licensed under the new
BSD license (3-clause). See the Stan Reference Manual
[Licenses section](https://mc-stan.org/docs/reference-manual/licensing.html)
for licensing terms for Stan.


#### Stan documentation: user's guide and reference manuals {-}

The Stan user's guide provides example models and programming
techniques for coding statistical models in Stan.
It also serves as an example-driven introduction to Bayesian modeling
and inference:

http://mc-stan.org/docs/stan-users-guide

Stan's modeling language is shared across all of its interfaces.
The Stan Language Reference Manual provides a concise definition
of the language syntax for all elements in the language.

http://mc-stan.org/docs/reference-manual

The Stan Functions Reference provides definitions and examples
for all the functions defined in the Stan math
library and available in the Stan programming language, including
all probability distributions.

http://mc-stan.org/docs/functions-reference.

#### Benefits of CmdStan {-}

- With every new Stan release, there is a corresponding CmdStan release,
therefore CmdStan provides access to the latest version of Stan,
and can be used to run the development version of Stan as well.

- Of the Stan interfaces, CmdStan has the lightest memory footprint,
therefore it can fit larger and more complex models.  It has
has the fewest dependencies, which makes it easier to run in limited
environments such as clusters.

- The output generated is in CSV format and can be post-processed using
other Stan interfaces or general tools.
