# MCMC Sampling

## Running the Sampler

To generate a sample from the posterior distribution of
the model conditioned on the data,
we run the executable program with the argument `sample` or `method=sample`
together with the input data.
The executable can be run from any directory.
Here, we run it in the directory which contains the Stan program and input data,
`<cmdstan-home>/examples/bernoulli`:
```
> cd examples/bernoulli
```

To execute sampling of the model under Linux or Mac, use:
```
> ./bernoulli sample data file=bernoulli.data.JSON
```

In Windows, the `./` prefix is not needed:

```
> bernoulli.exe sample data file=bernoulli.data.JSON
```

The output is the same across all supported platforms. First, the
configuration of the program is echoed to the standard output:

```
method = sample (Default)
  sample
    num_samples = 1000 (Default)
    num_warmup = 1000 (Default)
    save_warmup = 0 (Default)
    thin = 1 (Default)
    adapt
      engaged = 1 (Default)
      gamma = 0.050000000000000003 (Default)
      delta = 0.80000000000000004 (Default)
      kappa = 0.75 (Default)
      t0 = 10 (Default)
      init_buffer = 75 (Default)
      term_buffer = 50 (Default)
      window = 25 (Default)
    algorithm = hmc (Default)
      hmc
        engine = nuts (Default)
          nuts
            max_depth = 10 (Default)
        metric = diag_e (Default)
        metric_file =  (Default)
        stepsize = 1 (Default)
        stepsize_jitter = 0 (Default)
id = 0 (Default)
data
  file = bernoulli.data.json
init = 2 (Default)
random
  seed = 3252652196 (Default)
output
  file = output.csv (Default)
  diagnostic_file =  (Default)
  refresh = 100 (Default)
```

After the configuration has been displayed, a short timing message is
given.

```
Gradient evaluation took 1.2e-05 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.12 seconds.
Adjust your expectations accordingly!
```

Next, the sampler reports the iteration number, reporting the
percentage complete.

```
Iteration:    1 / 2000 [  0%]  (Warmup)
....
Iteration: 2000 / 2000 [100%]  (Sampling)
```

Finally, the sampler reports timing information:
```
 Elapsed Time: 0.007 seconds (Warm-up)
               0.017 seconds (Sampling)
               0.024 seconds (Total)
```

## Stan CSV Output File

Each execution of the model results in draws from a single Markov
chain being written to a file in comma-separated value (CSV) format.
The default name of the output file is `output.csv`.

The first part of the output file records the version of the
underlying Stan library and the configuration as comments (i.e., lines
beginning with the pound sign (`#`)).

```
# stan_version_major = 2
# stan_version_minor = 23
# stan_version_patch = 0
# model = bernoulli_model
# method = sample (Default)
#   sample
#     num_samples = 1000 (Default)
#     num_warmup = 1000 (Default)
...
# output
#   file = output.csv (Default)
#   diagnostic_file =  (Default)
#   refresh = 100 (Default)
```
This is followed by a CSV header indicating the names of the values
sampled.
```
lp__,accept_stat__,stepsize__,treedepth__,n_leapfrog__,divergent__,energy__,theta
```
The first output columns report the HMC sampler information:

- `lp__` - the unnormalized log probability of the model
- `accept_stat__ ` - the Metropolis acceptance probability averaged over samples in the slice
- `stepsize__ ` - integrator step size
- `treedepth__ ` - tree depth (NUTS sampler)
- `n_leapfrog__ ` - Number of leapfrog calculations (NUTS sampler)
- `divergent__ ` - has value `1` if trajectory diverged, otherwise `0`. (NUTS sampler)
- `energy__ ` - Hamiltonian value
- `int_time__ ` - Total integration time (HMC sampler)


The remaining columns correspond to model parameters. For the
Bernoulli model, it is just the final column, `theta`.

The header line is written to the output file before warmup begins.
If option `save_warmup` is set to `1`, the following lines will contain
the warmup draws.
The total number of warmup draws saved is `num_warmup` divided by `thin`, rounded up (i.e., `ceiling`).

Following the warmup draws (if any), are comments which record the results of adaptation:
the stepsize, and inverse mass metric used during sampling:

```
# Adaptation terminated
# Step size = 0.884484
# Diagonal elements of inverse mass matrix:
# 0.535006
```

The default sampler is NUTS with an adapted step size and a diagonal
inverse mass matrix. For this example, the step size is 0.884484, and
the inverse mass contains the single entry 0.535006 corresponding to
the parameter `theta`.

Draws from the posterior distribution are printed out next, each line
containing a single draw with the columns corresponding to the header.

```
-6.84097,0.974135,0.884484,1,3,0,6.89299,0.198853
-6.91767,0.985167,0.884484,1,1,0,6.92236,0.182295
-7.04879,0.976609,0.884484,1,1,0,7.05641,0.162299
-6.88712,1,0.884484,1,1,0,7.02101,0.188229
-7.22917,0.899446,0.884484,1,3,0,7.73663,0.383596
...
```

The output ends with timing details:
```
#  Elapsed Time: 0.007 seconds (Warm-up)
#                0.017 seconds (Sampling)
#                0.024 seconds (Total)
```

## Summarizing Sampler Output(s) with `stansummary`

The `stansummary` utility processes one or more output files from a run
or set of runs of Stan's HMC sampler given a model and data.
For all columns in the Stan csv output file `stansummary` reports a set of statistics
including mean, standard deviation, percentiles, effective number of samples, and $\hat{R}$ values.

To run `stansummary` on the output file generated
by the above run of the `bernoulli` model on Mac or Linux:

```
<cmdstan-home>/bin/stansummary output.csv
```

On Window, use backslashes to call the `stansummary.exe`.

```
<cmdstan-home>\bin\stansummary.exe output.csv
```

The stansummary output consists of one row of statistics per column
in the Stan csv output file.  Therefore, the first rows in the
stansummary report statistics over the sampler state.
The final row of output summarizes the estimates of the model variable `theta`:
```
Inference for Stan model: bernoulli_model
1 chains: each with iter=(1000); warmup=(0); thin=(1); 1000 iterations saved.

Warmup took (0.0070) seconds, 0.0070 seconds total
Sampling took (0.017) seconds, 0.017 seconds total

                Mean     MCSE   StdDev     5%   50%   95%    N_Eff  N_Eff/s    R_hat
lp__            -7.3  4.4e-02  7.9e-01   -8.7  -7.0  -6.8  3.2e+02  1.9e+04  1.0e+00
accept_stat__   0.92  3.7e-03  1.2e-01   0.65  0.98   1.0  9.9e+02  5.8e+04  1.0e+00
stepsize__      0.88      nan  2.8e-15   0.88  0.88  0.88      nan      nan      nan
treedepth__      1.4  1.6e-02  4.9e-01    1.0   1.0   2.0  9.7e+02  5.7e+04  1.0e+00
n_leapfrog__     2.6  5.0e-02  1.5e+00    1.0   3.0   7.0  8.5e+02  5.0e+04  1.0e+00
divergent__     0.00      nan  0.0e+00   0.00  0.00  0.00      nan      nan      nan
energy__         7.8  6.2e-02  1.1e+00    6.8   7.4   9.8  3.2e+02  1.9e+04  1.0e+00
theta           0.26  5.9e-03  1.2e-01  0.088  0.25  0.47  4.0e+02  2.3e+04  1.0e+00

Samples were drawn using hmc with nuts.
For each parameter, N_Eff is a crude measure of effective sample size,
and R_hat is the potential scale reduction factor on split chains (at 
convergence, R_hat=1).
```

In this example, we conditioned the model on a dataset consisting of the outcomes of
10 bernoulli trials, where only 2 trials reported success.  The 5%, 50%, and 95%
percentile values for `theta` reflect the uncertainty in our estimate, due to the
small amount of data, given the prior of `beta(1, 1)`


The command `bin/stansummary` can be called with more than one
csv file by separating filenames with spaces. It will also take
wildcards in specifying filenames. A typical usage of Stan from the
command line would first create one or more Markov chains by calling
the model executable, typically in parallel, writing the output CSV
file for each into its own directory. After all of the processes are
finished, the results would be analyzed using `stansummary` to
assess convergence and inspect the means and quantiles of the fitted
variables. Additionally, downstream inferences may be performed using
the draws (e.g., to make decisions or predictions for unseen data).
