name: Deploy to Github Pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - .github/workflows/deploy.yml
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./docs/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
