name: Render and Publish

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - .github/workflows/deploy.yml
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  build-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
